package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.Avainsana;
import fi.csc.avaa.tupa.db.service.AvainsanaLocalServiceUtil;

/**
 * The extended model base implementation for the Avainsana service. Represents a row in the &quot;avainsana&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AvainsanaImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see AvainsanaImpl
 * @see fi.csc.avaa.tupa.db.model.Avainsana
 * @generated
 */
public abstract class AvainsanaBaseImpl extends AvainsanaModelImpl
    implements Avainsana {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a avainsana model instance should use the {@link Avainsana} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AvainsanaLocalServiceUtil.addAvainsana(this);
        } else {
            AvainsanaLocalServiceUtil.updateAvainsana(this);
        }
    }
}
