package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot;
import fi.csc.avaa.tupa.db.service.Infra_YhteystiedotLocalServiceUtil;

/**
 * The extended model base implementation for the Infra_Yhteystiedot service. Represents a row in the &quot;infra_yhteystiedot&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Infra_YhteystiedotImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see Infra_YhteystiedotImpl
 * @see fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot
 * @generated
 */
public abstract class Infra_YhteystiedotBaseImpl
    extends Infra_YhteystiedotModelImpl implements Infra_Yhteystiedot {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a infra_ yhteystiedot model instance should use the {@link Infra_Yhteystiedot} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Infra_YhteystiedotLocalServiceUtil.addInfra_Yhteystiedot(this);
        } else {
            Infra_YhteystiedotLocalServiceUtil.updateInfra_Yhteystiedot(this);
        }
    }
}
