package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.Infra_Vastuuorganisaatiot;
import fi.csc.avaa.tupa.db.service.Infra_VastuuorganisaatiotLocalServiceUtil;

/**
 * The extended model base implementation for the Infra_Vastuuorganisaatiot service. Represents a row in the &quot;infra_vastuuorganisaatiot&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Infra_VastuuorganisaatiotImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see Infra_VastuuorganisaatiotImpl
 * @see fi.csc.avaa.tupa.db.model.Infra_Vastuuorganisaatiot
 * @generated
 */
public abstract class Infra_VastuuorganisaatiotBaseImpl
    extends Infra_VastuuorganisaatiotModelImpl
    implements Infra_Vastuuorganisaatiot {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a infra_ vastuuorganisaatiot model instance should use the {@link Infra_Vastuuorganisaatiot} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Infra_VastuuorganisaatiotLocalServiceUtil.addInfra_Vastuuorganisaatiot(this);
        } else {
            Infra_VastuuorganisaatiotLocalServiceUtil.updateInfra_Vastuuorganisaatiot(this);
        }
    }
}
