package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import fi.csc.avaa.tupa.db.model.Infra_Vastuuorganisaatiot;
import fi.csc.avaa.tupa.db.model.Infra_VastuuorganisaatiotModel;
import fi.csc.avaa.tupa.db.service.persistence.Infra_VastuuorganisaatiotPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Infra_Vastuuorganisaatiot service. Represents a row in the &quot;infra_vastuuorganisaatiot&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link fi.csc.avaa.tupa.db.model.Infra_VastuuorganisaatiotModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Infra_VastuuorganisaatiotImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see Infra_VastuuorganisaatiotImpl
 * @see fi.csc.avaa.tupa.db.model.Infra_Vastuuorganisaatiot
 * @see fi.csc.avaa.tupa.db.model.Infra_VastuuorganisaatiotModel
 * @generated
 */
public class Infra_VastuuorganisaatiotModelImpl extends BaseModelImpl<Infra_Vastuuorganisaatiot>
    implements Infra_VastuuorganisaatiotModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a infra_ vastuuorganisaatiot model instance should use the {@link fi.csc.avaa.tupa.db.model.Infra_Vastuuorganisaatiot} interface instead.
     */
    public static final String TABLE_NAME = "infra_vastuuorganisaatiot";
    public static final Object[][] TABLE_COLUMNS = {
            { "infra_id", Types.INTEGER },
            { "organisaatio_id", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table infra_vastuuorganisaatiot (infra_id INTEGER not null,organisaatio_id INTEGER not null,primary key (infra_id, organisaatio_id))";
    public static final String TABLE_SQL_DROP = "drop table infra_vastuuorganisaatiot";
    public static final String ORDER_BY_JPQL = " ORDER BY infra_Vastuuorganisaatiot.id.infra_id ASC, infra_Vastuuorganisaatiot.id.organisaatio_id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY infra_vastuuorganisaatiot.infra_id ASC, infra_vastuuorganisaatiot.organisaatio_id ASC";
    public static final String DATA_SOURCE = "tupa";
    public static final String SESSION_FACTORY = "tupaSessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.fi.csc.avaa.tupa.db.model.Infra_Vastuuorganisaatiot"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.fi.csc.avaa.tupa.db.model.Infra_Vastuuorganisaatiot"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.fi.csc.avaa.tupa.db.model.Infra_Vastuuorganisaatiot"));
    private static ClassLoader _classLoader = Infra_Vastuuorganisaatiot.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Infra_Vastuuorganisaatiot.class
        };
    private int _infra_id;
    private int _organisaatio_id;
    private Infra_Vastuuorganisaatiot _escapedModel;

    public Infra_VastuuorganisaatiotModelImpl() {
    }

    @Override
    public Infra_VastuuorganisaatiotPK getPrimaryKey() {
        return new Infra_VastuuorganisaatiotPK(_infra_id, _organisaatio_id);
    }

    @Override
    public void setPrimaryKey(Infra_VastuuorganisaatiotPK primaryKey) {
        setInfra_id(primaryKey.infra_id);
        setOrganisaatio_id(primaryKey.organisaatio_id);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return new Infra_VastuuorganisaatiotPK(_infra_id, _organisaatio_id);
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey((Infra_VastuuorganisaatiotPK) primaryKeyObj);
    }

    @Override
    public Class<?> getModelClass() {
        return Infra_Vastuuorganisaatiot.class;
    }

    @Override
    public String getModelClassName() {
        return Infra_Vastuuorganisaatiot.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("infra_id", getInfra_id());
        attributes.put("organisaatio_id", getOrganisaatio_id());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer infra_id = (Integer) attributes.get("infra_id");

        if (infra_id != null) {
            setInfra_id(infra_id);
        }

        Integer organisaatio_id = (Integer) attributes.get("organisaatio_id");

        if (organisaatio_id != null) {
            setOrganisaatio_id(organisaatio_id);
        }
    }

    @Override
    public int getInfra_id() {
        return _infra_id;
    }

    @Override
    public void setInfra_id(int infra_id) {
        _infra_id = infra_id;
    }

    @Override
    public int getOrganisaatio_id() {
        return _organisaatio_id;
    }

    @Override
    public void setOrganisaatio_id(int organisaatio_id) {
        _organisaatio_id = organisaatio_id;
    }

    @Override
    public Infra_Vastuuorganisaatiot toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Infra_Vastuuorganisaatiot) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        Infra_VastuuorganisaatiotImpl infra_VastuuorganisaatiotImpl = new Infra_VastuuorganisaatiotImpl();

        infra_VastuuorganisaatiotImpl.setInfra_id(getInfra_id());
        infra_VastuuorganisaatiotImpl.setOrganisaatio_id(getOrganisaatio_id());

        infra_VastuuorganisaatiotImpl.resetOriginalValues();

        return infra_VastuuorganisaatiotImpl;
    }

    @Override
    public int compareTo(Infra_Vastuuorganisaatiot infra_Vastuuorganisaatiot) {
        Infra_VastuuorganisaatiotPK primaryKey = infra_Vastuuorganisaatiot.getPrimaryKey();

        return getPrimaryKey().compareTo(primaryKey);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Infra_Vastuuorganisaatiot)) {
            return false;
        }

        Infra_Vastuuorganisaatiot infra_Vastuuorganisaatiot = (Infra_Vastuuorganisaatiot) obj;

        Infra_VastuuorganisaatiotPK primaryKey = infra_Vastuuorganisaatiot.getPrimaryKey();

        if (getPrimaryKey().equals(primaryKey)) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey().hashCode();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Infra_Vastuuorganisaatiot> toCacheModel() {
        Infra_VastuuorganisaatiotCacheModel infra_VastuuorganisaatiotCacheModel = new Infra_VastuuorganisaatiotCacheModel();

        infra_VastuuorganisaatiotCacheModel.infra_id = getInfra_id();

        infra_VastuuorganisaatiotCacheModel.organisaatio_id = getOrganisaatio_id();

        return infra_VastuuorganisaatiotCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(5);

        sb.append("{infra_id=");
        sb.append(getInfra_id());
        sb.append(", organisaatio_id=");
        sb.append(getOrganisaatio_id());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(10);

        sb.append("<model><model-name>");
        sb.append("fi.csc.avaa.tupa.db.model.Infra_Vastuuorganisaatiot");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>infra_id</column-name><column-value><![CDATA[");
        sb.append(getInfra_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>organisaatio_id</column-name><column-value><![CDATA[");
        sb.append(getOrganisaatio_id());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
