package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.Kayttoehto;
import fi.csc.avaa.tupa.db.service.KayttoehtoLocalServiceUtil;

/**
 * The extended model base implementation for the Kayttoehto service. Represents a row in the &quot;kayttoehto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KayttoehtoImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see KayttoehtoImpl
 * @see fi.csc.avaa.tupa.db.model.Kayttoehto
 * @generated
 */
public abstract class KayttoehtoBaseImpl extends KayttoehtoModelImpl
    implements Kayttoehto {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a kayttoehto model instance should use the {@link Kayttoehto} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            KayttoehtoLocalServiceUtil.addKayttoehto(this);
        } else {
            KayttoehtoLocalServiceUtil.updateKayttoehto(this);
        }
    }
}
