package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import fi.csc.avaa.tupa.db.model.Organisaatio;
import fi.csc.avaa.tupa.db.model.OrganisaatioModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Organisaatio service. Represents a row in the &quot;organisaatio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link fi.csc.avaa.tupa.db.model.OrganisaatioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OrganisaatioImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see OrganisaatioImpl
 * @see fi.csc.avaa.tupa.db.model.Organisaatio
 * @see fi.csc.avaa.tupa.db.model.OrganisaatioModel
 * @generated
 */
public class OrganisaatioModelImpl extends BaseModelImpl<Organisaatio>
    implements OrganisaatioModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a organisaatio model instance should use the {@link fi.csc.avaa.tupa.db.model.Organisaatio} interface instead.
     */
    public static final String TABLE_NAME = "organisaatio";
    public static final Object[][] TABLE_COLUMNS = {
            { "organisaatio_id", Types.INTEGER },
            { "nimi", Types.VARCHAR },
            { "name", Types.VARCHAR },
            { "maa", Types.VARCHAR },
            { "ISNI", Types.VARCHAR },
            { "crmid", Types.VARCHAR },
            { "emo_organisaatio", Types.INTEGER },
            { "kv_isanta", Types.BOOLEAN }
        };
    public static final String TABLE_SQL_CREATE = "create table organisaatio (organisaatio_id INTEGER not null primary key,nimi VARCHAR(75) null,name VARCHAR(75) null,maa VARCHAR(75) null,ISNI VARCHAR(75) null,crmid VARCHAR(75) null,emo_organisaatio INTEGER,kv_isanta BOOLEAN)";
    public static final String TABLE_SQL_DROP = "drop table organisaatio";
    public static final String ORDER_BY_JPQL = " ORDER BY organisaatio.organisaatio_id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY organisaatio.organisaatio_id ASC";
    public static final String DATA_SOURCE = "tupa";
    public static final String SESSION_FACTORY = "tupaSessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.fi.csc.avaa.tupa.db.model.Organisaatio"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.fi.csc.avaa.tupa.db.model.Organisaatio"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.fi.csc.avaa.tupa.db.model.Organisaatio"));
    private static ClassLoader _classLoader = Organisaatio.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Organisaatio.class
        };
    private int _organisaatio_id;
    private String _nimi;
    private String _name;
    private String _maa;
    private String _ISNI;
    private String _crmid;
    private int _emo_organisaatio;
    private boolean _kv_isanta;
    private Organisaatio _escapedModel;

    public OrganisaatioModelImpl() {
    }

    @Override
    public int getPrimaryKey() {
        return _organisaatio_id;
    }

    @Override
    public void setPrimaryKey(int primaryKey) {
        setOrganisaatio_id(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _organisaatio_id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Integer) primaryKeyObj).intValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Organisaatio.class;
    }

    @Override
    public String getModelClassName() {
        return Organisaatio.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("organisaatio_id", getOrganisaatio_id());
        attributes.put("nimi", getNimi());
        attributes.put("name", getName());
        attributes.put("maa", getMaa());
        attributes.put("ISNI", getISNI());
        attributes.put("crmid", getCrmid());
        attributes.put("emo_organisaatio", getEmo_organisaatio());
        attributes.put("kv_isanta", getKv_isanta());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer organisaatio_id = (Integer) attributes.get("organisaatio_id");

        if (organisaatio_id != null) {
            setOrganisaatio_id(organisaatio_id);
        }

        String nimi = (String) attributes.get("nimi");

        if (nimi != null) {
            setNimi(nimi);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String maa = (String) attributes.get("maa");

        if (maa != null) {
            setMaa(maa);
        }

        String ISNI = (String) attributes.get("ISNI");

        if (ISNI != null) {
            setISNI(ISNI);
        }

        String crmid = (String) attributes.get("crmid");

        if (crmid != null) {
            setCrmid(crmid);
        }

        Integer emo_organisaatio = (Integer) attributes.get("emo_organisaatio");

        if (emo_organisaatio != null) {
            setEmo_organisaatio(emo_organisaatio);
        }

        Boolean kv_isanta = (Boolean) attributes.get("kv_isanta");

        if (kv_isanta != null) {
            setKv_isanta(kv_isanta);
        }
    }

    @Override
    public int getOrganisaatio_id() {
        return _organisaatio_id;
    }

    @Override
    public void setOrganisaatio_id(int organisaatio_id) {
        _organisaatio_id = organisaatio_id;
    }

    @Override
    public String getNimi() {
        if (_nimi == null) {
            return StringPool.BLANK;
        } else {
            return _nimi;
        }
    }

    @Override
    public void setNimi(String nimi) {
        _nimi = nimi;
    }

    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @Override
    public String getMaa() {
        if (_maa == null) {
            return StringPool.BLANK;
        } else {
            return _maa;
        }
    }

    @Override
    public void setMaa(String maa) {
        _maa = maa;
    }

    @Override
    public String getISNI() {
        if (_ISNI == null) {
            return StringPool.BLANK;
        } else {
            return _ISNI;
        }
    }

    @Override
    public void setISNI(String ISNI) {
        _ISNI = ISNI;
    }

    @Override
    public String getCrmid() {
        if (_crmid == null) {
            return StringPool.BLANK;
        } else {
            return _crmid;
        }
    }

    @Override
    public void setCrmid(String crmid) {
        _crmid = crmid;
    }

    @Override
    public int getEmo_organisaatio() {
        return _emo_organisaatio;
    }

    @Override
    public void setEmo_organisaatio(int emo_organisaatio) {
        _emo_organisaatio = emo_organisaatio;
    }

    @Override
    public boolean getKv_isanta() {
        return _kv_isanta;
    }

    @Override
    public boolean isKv_isanta() {
        return _kv_isanta;
    }

    @Override
    public void setKv_isanta(boolean kv_isanta) {
        _kv_isanta = kv_isanta;
    }

    @Override
    public Organisaatio toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Organisaatio) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        OrganisaatioImpl organisaatioImpl = new OrganisaatioImpl();

        organisaatioImpl.setOrganisaatio_id(getOrganisaatio_id());
        organisaatioImpl.setNimi(getNimi());
        organisaatioImpl.setName(getName());
        organisaatioImpl.setMaa(getMaa());
        organisaatioImpl.setISNI(getISNI());
        organisaatioImpl.setCrmid(getCrmid());
        organisaatioImpl.setEmo_organisaatio(getEmo_organisaatio());
        organisaatioImpl.setKv_isanta(getKv_isanta());

        organisaatioImpl.resetOriginalValues();

        return organisaatioImpl;
    }

    @Override
    public int compareTo(Organisaatio organisaatio) {
        int primaryKey = organisaatio.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Organisaatio)) {
            return false;
        }

        Organisaatio organisaatio = (Organisaatio) obj;

        int primaryKey = organisaatio.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Organisaatio> toCacheModel() {
        OrganisaatioCacheModel organisaatioCacheModel = new OrganisaatioCacheModel();

        organisaatioCacheModel.organisaatio_id = getOrganisaatio_id();

        organisaatioCacheModel.nimi = getNimi();

        String nimi = organisaatioCacheModel.nimi;

        if ((nimi != null) && (nimi.length() == 0)) {
            organisaatioCacheModel.nimi = null;
        }

        organisaatioCacheModel.name = getName();

        String name = organisaatioCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            organisaatioCacheModel.name = null;
        }

        organisaatioCacheModel.maa = getMaa();

        String maa = organisaatioCacheModel.maa;

        if ((maa != null) && (maa.length() == 0)) {
            organisaatioCacheModel.maa = null;
        }

        organisaatioCacheModel.ISNI = getISNI();

        String ISNI = organisaatioCacheModel.ISNI;

        if ((ISNI != null) && (ISNI.length() == 0)) {
            organisaatioCacheModel.ISNI = null;
        }

        organisaatioCacheModel.crmid = getCrmid();

        String crmid = organisaatioCacheModel.crmid;

        if ((crmid != null) && (crmid.length() == 0)) {
            organisaatioCacheModel.crmid = null;
        }

        organisaatioCacheModel.emo_organisaatio = getEmo_organisaatio();

        organisaatioCacheModel.kv_isanta = getKv_isanta();

        return organisaatioCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(17);

        sb.append("{organisaatio_id=");
        sb.append(getOrganisaatio_id());
        sb.append(", nimi=");
        sb.append(getNimi());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", maa=");
        sb.append(getMaa());
        sb.append(", ISNI=");
        sb.append(getISNI());
        sb.append(", crmid=");
        sb.append(getCrmid());
        sb.append(", emo_organisaatio=");
        sb.append(getEmo_organisaatio());
        sb.append(", kv_isanta=");
        sb.append(getKv_isanta());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(28);

        sb.append("<model><model-name>");
        sb.append("fi.csc.avaa.tupa.db.model.Organisaatio");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>organisaatio_id</column-name><column-value><![CDATA[");
        sb.append(getOrganisaatio_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>nimi</column-name><column-value><![CDATA[");
        sb.append(getNimi());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>maa</column-name><column-value><![CDATA[");
        sb.append(getMaa());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ISNI</column-name><column-value><![CDATA[");
        sb.append(getISNI());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>crmid</column-name><column-value><![CDATA[");
        sb.append(getCrmid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>emo_organisaatio</column-name><column-value><![CDATA[");
        sb.append(getEmo_organisaatio());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>kv_isanta</column-name><column-value><![CDATA[");
        sb.append(getKv_isanta());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
