package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.Palvelu_Palvelutyypit;
import fi.csc.avaa.tupa.db.service.Palvelu_PalvelutyypitLocalServiceUtil;

/**
 * The extended model base implementation for the Palvelu_Palvelutyypit service. Represents a row in the &quot;palvelu_palvelutyypit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Palvelu_PalvelutyypitImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see Palvelu_PalvelutyypitImpl
 * @see fi.csc.avaa.tupa.db.model.Palvelu_Palvelutyypit
 * @generated
 */
public abstract class Palvelu_PalvelutyypitBaseImpl
    extends Palvelu_PalvelutyypitModelImpl implements Palvelu_Palvelutyypit {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a palvelu_ palvelutyypit model instance should use the {@link Palvelu_Palvelutyypit} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Palvelu_PalvelutyypitLocalServiceUtil.addPalvelu_Palvelutyypit(this);
        } else {
            Palvelu_PalvelutyypitLocalServiceUtil.updatePalvelu_Palvelutyypit(this);
        }
    }
}
