package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.Yhteystieto;
import fi.csc.avaa.tupa.db.service.YhteystietoLocalServiceUtil;

/**
 * The extended model base implementation for the Yhteystieto service. Represents a row in the &quot;yhteystieto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link YhteystietoImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see YhteystietoImpl
 * @see fi.csc.avaa.tupa.db.model.Yhteystieto
 * @generated
 */
public abstract class YhteystietoBaseImpl extends YhteystietoModelImpl
    implements Yhteystieto {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a yhteystieto model instance should use the {@link Yhteystieto} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            YhteystietoLocalServiceUtil.addYhteystieto(this);
        } else {
            YhteystietoLocalServiceUtil.updateYhteystieto(this);
        }
    }
}
