/**
 * 
 */
package fi.csc.avaa.tupa.common;

/**
 * @author jmlehtin
 *
 */
public enum SeliteType {

	PALVELUTYYPPI,
	PAIKKATYYPPI,
	KAYTTOEHTO_SAAVUTETTAVUUS,
	KAYTTOEHTO_ANONYMITEETTI,
	KAYTTOEHTO_MAKSULLISUUS,
	KAYTTOEHTO_TULOSTEN_JULKAISUVELVOITE,
	KAYTTOEHTO_TUOTOKSIEN_JULKAISUVELVOITE,
	KAYTTOEHTO_OSAAMISEN_AVOIMUUS,
	KAYTTOEHTO_SEURANTATYOKALUT,
	KAYTTOEHTO_TULOSTEN_LISENSOINTI
	
}
