package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot;
import fi.csc.avaa.tupa.db.model.Infra_YhteystiedotModel;
import fi.csc.avaa.tupa.db.service.persistence.Infra_YhteystiedotPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Infra_Yhteystiedot service. Represents a row in the &quot;infra_yhteystiedot&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link fi.csc.avaa.tupa.db.model.Infra_YhteystiedotModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Infra_YhteystiedotImpl}.
 * </p>
 *
 * @author CSC
 * @see Infra_YhteystiedotImpl
 * @see fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot
 * @see fi.csc.avaa.tupa.db.model.Infra_YhteystiedotModel
 * @generated
 */
public class Infra_YhteystiedotModelImpl extends BaseModelImpl<Infra_Yhteystiedot>
    implements Infra_YhteystiedotModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a infra_ yhteystiedot model instance should use the {@link fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot} interface instead.
     */
    public static final String TABLE_NAME = "infra_yhteystiedot";
    public static final Object[][] TABLE_COLUMNS = {
            { "infra_id", Types.INTEGER },
            { "yhteystieto_id", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table infra_yhteystiedot (infra_id INTEGER not null,yhteystieto_id INTEGER not null,primary key (infra_id, yhteystieto_id))";
    public static final String TABLE_SQL_DROP = "drop table infra_yhteystiedot";
    public static final String ORDER_BY_JPQL = " ORDER BY infra_Yhteystiedot.id.infra_id ASC, infra_Yhteystiedot.id.yhteystieto_id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY infra_yhteystiedot.infra_id ASC, infra_yhteystiedot.yhteystieto_id ASC";
    public static final String DATA_SOURCE = "tupa";
    public static final String SESSION_FACTORY = "tupaSessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot"));
    private static ClassLoader _classLoader = Infra_Yhteystiedot.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Infra_Yhteystiedot.class
        };
    private int _infra_id;
    private int _yhteystieto_id;
    private Infra_Yhteystiedot _escapedModel;

    public Infra_YhteystiedotModelImpl() {
    }

    @Override
    public Infra_YhteystiedotPK getPrimaryKey() {
        return new Infra_YhteystiedotPK(_infra_id, _yhteystieto_id);
    }

    @Override
    public void setPrimaryKey(Infra_YhteystiedotPK primaryKey) {
        setInfra_id(primaryKey.infra_id);
        setYhteystieto_id(primaryKey.yhteystieto_id);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return new Infra_YhteystiedotPK(_infra_id, _yhteystieto_id);
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey((Infra_YhteystiedotPK) primaryKeyObj);
    }

    @Override
    public Class<?> getModelClass() {
        return Infra_Yhteystiedot.class;
    }

    @Override
    public String getModelClassName() {
        return Infra_Yhteystiedot.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("infra_id", getInfra_id());
        attributes.put("yhteystieto_id", getYhteystieto_id());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer infra_id = (Integer) attributes.get("infra_id");

        if (infra_id != null) {
            setInfra_id(infra_id);
        }

        Integer yhteystieto_id = (Integer) attributes.get("yhteystieto_id");

        if (yhteystieto_id != null) {
            setYhteystieto_id(yhteystieto_id);
        }
    }

    @Override
    public int getInfra_id() {
        return _infra_id;
    }

    @Override
    public void setInfra_id(int infra_id) {
        _infra_id = infra_id;
    }

    @Override
    public int getYhteystieto_id() {
        return _yhteystieto_id;
    }

    @Override
    public void setYhteystieto_id(int yhteystieto_id) {
        _yhteystieto_id = yhteystieto_id;
    }

    @Override
    public Infra_Yhteystiedot toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Infra_Yhteystiedot) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        Infra_YhteystiedotImpl infra_YhteystiedotImpl = new Infra_YhteystiedotImpl();

        infra_YhteystiedotImpl.setInfra_id(getInfra_id());
        infra_YhteystiedotImpl.setYhteystieto_id(getYhteystieto_id());

        infra_YhteystiedotImpl.resetOriginalValues();

        return infra_YhteystiedotImpl;
    }

    @Override
    public int compareTo(Infra_Yhteystiedot infra_Yhteystiedot) {
        Infra_YhteystiedotPK primaryKey = infra_Yhteystiedot.getPrimaryKey();

        return getPrimaryKey().compareTo(primaryKey);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Infra_Yhteystiedot)) {
            return false;
        }

        Infra_Yhteystiedot infra_Yhteystiedot = (Infra_Yhteystiedot) obj;

        Infra_YhteystiedotPK primaryKey = infra_Yhteystiedot.getPrimaryKey();

        if (getPrimaryKey().equals(primaryKey)) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey().hashCode();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Infra_Yhteystiedot> toCacheModel() {
        Infra_YhteystiedotCacheModel infra_YhteystiedotCacheModel = new Infra_YhteystiedotCacheModel();

        infra_YhteystiedotCacheModel.infra_id = getInfra_id();

        infra_YhteystiedotCacheModel.yhteystieto_id = getYhteystieto_id();

        return infra_YhteystiedotCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(5);

        sb.append("{infra_id=");
        sb.append(getInfra_id());
        sb.append(", yhteystieto_id=");
        sb.append(getYhteystieto_id());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(10);

        sb.append("<model><model-name>");
        sb.append("fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>infra_id</column-name><column-value><![CDATA[");
        sb.append(getInfra_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>yhteystieto_id</column-name><column-value><![CDATA[");
        sb.append(getYhteystieto_id());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
