package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.Infra_Identifier;
import fi.csc.avaa.tupa.db.service.Infra_IdentifierLocalServiceUtil;

/**
 * The extended model base implementation for the Infra_Identifier service. Represents a row in the &quot;infra_identifier&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Infra_IdentifierImpl}.
 * </p>
 *
 * @author CSC
 * @see Infra_IdentifierImpl
 * @see fi.csc.avaa.tupa.db.model.Infra_Identifier
 * @generated
 */
public abstract class Infra_IdentifierBaseImpl extends Infra_IdentifierModelImpl
    implements Infra_Identifier {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a infra_ identifier model instance should use the {@link Infra_Identifier} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Infra_IdentifierLocalServiceUtil.addInfra_Identifier(this);
        } else {
            Infra_IdentifierLocalServiceUtil.updateInfra_Identifier(this);
        }
    }
}
