package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.Infra_Palvelut;
import fi.csc.avaa.tupa.db.service.Infra_PalvelutLocalServiceUtil;

/**
 * The extended model base implementation for the Infra_Palvelut service. Represents a row in the &quot;infra_palvelut&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Infra_PalvelutImpl}.
 * </p>
 *
 * @author CSC
 * @see Infra_PalvelutImpl
 * @see fi.csc.avaa.tupa.db.model.Infra_Palvelut
 * @generated
 */
public abstract class Infra_PalvelutBaseImpl extends Infra_PalvelutModelImpl
    implements Infra_Palvelut {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a infra_ palvelut model instance should use the {@link Infra_Palvelut} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Infra_PalvelutLocalServiceUtil.addInfra_Palvelut(this);
        } else {
            Infra_PalvelutLocalServiceUtil.updateInfra_Palvelut(this);
        }
    }
}
