package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import fi.csc.avaa.tupa.db.model.Infra_Palvelut;
import fi.csc.avaa.tupa.db.model.Infra_PalvelutModel;
import fi.csc.avaa.tupa.db.service.persistence.Infra_PalvelutPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Infra_Palvelut service. Represents a row in the &quot;infra_palvelut&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link fi.csc.avaa.tupa.db.model.Infra_PalvelutModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Infra_PalvelutImpl}.
 * </p>
 *
 * @author CSC
 * @see Infra_PalvelutImpl
 * @see fi.csc.avaa.tupa.db.model.Infra_Palvelut
 * @see fi.csc.avaa.tupa.db.model.Infra_PalvelutModel
 * @generated
 */
public class Infra_PalvelutModelImpl extends BaseModelImpl<Infra_Palvelut>
    implements Infra_PalvelutModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a infra_ palvelut model instance should use the {@link fi.csc.avaa.tupa.db.model.Infra_Palvelut} interface instead.
     */
    public static final String TABLE_NAME = "infra_palvelut";
    public static final Object[][] TABLE_COLUMNS = {
            { "infra_id", Types.INTEGER },
            { "palvelu_id", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table infra_palvelut (infra_id INTEGER not null,palvelu_id INTEGER not null,primary key (infra_id, palvelu_id))";
    public static final String TABLE_SQL_DROP = "drop table infra_palvelut";
    public static final String ORDER_BY_JPQL = " ORDER BY infra_Palvelut.id.infra_id ASC, infra_Palvelut.id.palvelu_id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY infra_palvelut.infra_id ASC, infra_palvelut.palvelu_id ASC";
    public static final String DATA_SOURCE = "tupa";
    public static final String SESSION_FACTORY = "tupaSessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.fi.csc.avaa.tupa.db.model.Infra_Palvelut"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.fi.csc.avaa.tupa.db.model.Infra_Palvelut"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.fi.csc.avaa.tupa.db.model.Infra_Palvelut"));
    private static ClassLoader _classLoader = Infra_Palvelut.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Infra_Palvelut.class
        };
    private int _infra_id;
    private int _palvelu_id;
    private Infra_Palvelut _escapedModel;

    public Infra_PalvelutModelImpl() {
    }

    @Override
    public Infra_PalvelutPK getPrimaryKey() {
        return new Infra_PalvelutPK(_infra_id, _palvelu_id);
    }

    @Override
    public void setPrimaryKey(Infra_PalvelutPK primaryKey) {
        setInfra_id(primaryKey.infra_id);
        setPalvelu_id(primaryKey.palvelu_id);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return new Infra_PalvelutPK(_infra_id, _palvelu_id);
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey((Infra_PalvelutPK) primaryKeyObj);
    }

    @Override
    public Class<?> getModelClass() {
        return Infra_Palvelut.class;
    }

    @Override
    public String getModelClassName() {
        return Infra_Palvelut.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("infra_id", getInfra_id());
        attributes.put("palvelu_id", getPalvelu_id());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer infra_id = (Integer) attributes.get("infra_id");

        if (infra_id != null) {
            setInfra_id(infra_id);
        }

        Integer palvelu_id = (Integer) attributes.get("palvelu_id");

        if (palvelu_id != null) {
            setPalvelu_id(palvelu_id);
        }
    }

    @Override
    public int getInfra_id() {
        return _infra_id;
    }

    @Override
    public void setInfra_id(int infra_id) {
        _infra_id = infra_id;
    }

    @Override
    public int getPalvelu_id() {
        return _palvelu_id;
    }

    @Override
    public void setPalvelu_id(int palvelu_id) {
        _palvelu_id = palvelu_id;
    }

    @Override
    public Infra_Palvelut toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Infra_Palvelut) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        Infra_PalvelutImpl infra_PalvelutImpl = new Infra_PalvelutImpl();

        infra_PalvelutImpl.setInfra_id(getInfra_id());
        infra_PalvelutImpl.setPalvelu_id(getPalvelu_id());

        infra_PalvelutImpl.resetOriginalValues();

        return infra_PalvelutImpl;
    }

    @Override
    public int compareTo(Infra_Palvelut infra_Palvelut) {
        Infra_PalvelutPK primaryKey = infra_Palvelut.getPrimaryKey();

        return getPrimaryKey().compareTo(primaryKey);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Infra_Palvelut)) {
            return false;
        }

        Infra_Palvelut infra_Palvelut = (Infra_Palvelut) obj;

        Infra_PalvelutPK primaryKey = infra_Palvelut.getPrimaryKey();

        if (getPrimaryKey().equals(primaryKey)) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey().hashCode();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Infra_Palvelut> toCacheModel() {
        Infra_PalvelutCacheModel infra_PalvelutCacheModel = new Infra_PalvelutCacheModel();

        infra_PalvelutCacheModel.infra_id = getInfra_id();

        infra_PalvelutCacheModel.palvelu_id = getPalvelu_id();

        return infra_PalvelutCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(5);

        sb.append("{infra_id=");
        sb.append(getInfra_id());
        sb.append(", palvelu_id=");
        sb.append(getPalvelu_id());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(10);

        sb.append("<model><model-name>");
        sb.append("fi.csc.avaa.tupa.db.model.Infra_Palvelut");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>infra_id</column-name><column-value><![CDATA[");
        sb.append(getInfra_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>palvelu_id</column-name><column-value><![CDATA[");
        sb.append(getPalvelu_id());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
