package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import fi.csc.avaa.tupa.db.model.Infra_Avainsanat;
import fi.csc.avaa.tupa.db.model.Infra_AvainsanatModel;
import fi.csc.avaa.tupa.db.service.persistence.Infra_AvainsanatPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Infra_Avainsanat service. Represents a row in the &quot;infra_avainsanat&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link fi.csc.avaa.tupa.db.model.Infra_AvainsanatModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Infra_AvainsanatImpl}.
 * </p>
 *
 * @author CSC
 * @see Infra_AvainsanatImpl
 * @see fi.csc.avaa.tupa.db.model.Infra_Avainsanat
 * @see fi.csc.avaa.tupa.db.model.Infra_AvainsanatModel
 * @generated
 */
public class Infra_AvainsanatModelImpl extends BaseModelImpl<Infra_Avainsanat>
    implements Infra_AvainsanatModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a infra_ avainsanat model instance should use the {@link fi.csc.avaa.tupa.db.model.Infra_Avainsanat} interface instead.
     */
    public static final String TABLE_NAME = "infra_avainsanat";
    public static final Object[][] TABLE_COLUMNS = {
            { "infra_id", Types.INTEGER },
            { "avainsana_id", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table infra_avainsanat (infra_id INTEGER not null,avainsana_id INTEGER not null,primary key (infra_id, avainsana_id))";
    public static final String TABLE_SQL_DROP = "drop table infra_avainsanat";
    public static final String ORDER_BY_JPQL = " ORDER BY infra_Avainsanat.id.infra_id ASC, infra_Avainsanat.id.avainsana_id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY infra_avainsanat.infra_id ASC, infra_avainsanat.avainsana_id ASC";
    public static final String DATA_SOURCE = "tupa";
    public static final String SESSION_FACTORY = "tupaSessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.fi.csc.avaa.tupa.db.model.Infra_Avainsanat"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.fi.csc.avaa.tupa.db.model.Infra_Avainsanat"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.fi.csc.avaa.tupa.db.model.Infra_Avainsanat"));
    private static ClassLoader _classLoader = Infra_Avainsanat.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Infra_Avainsanat.class
        };
    private int _infra_id;
    private int _avainsana_id;
    private Infra_Avainsanat _escapedModel;

    public Infra_AvainsanatModelImpl() {
    }

    @Override
    public Infra_AvainsanatPK getPrimaryKey() {
        return new Infra_AvainsanatPK(_infra_id, _avainsana_id);
    }

    @Override
    public void setPrimaryKey(Infra_AvainsanatPK primaryKey) {
        setInfra_id(primaryKey.infra_id);
        setAvainsana_id(primaryKey.avainsana_id);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return new Infra_AvainsanatPK(_infra_id, _avainsana_id);
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey((Infra_AvainsanatPK) primaryKeyObj);
    }

    @Override
    public Class<?> getModelClass() {
        return Infra_Avainsanat.class;
    }

    @Override
    public String getModelClassName() {
        return Infra_Avainsanat.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("infra_id", getInfra_id());
        attributes.put("avainsana_id", getAvainsana_id());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer infra_id = (Integer) attributes.get("infra_id");

        if (infra_id != null) {
            setInfra_id(infra_id);
        }

        Integer avainsana_id = (Integer) attributes.get("avainsana_id");

        if (avainsana_id != null) {
            setAvainsana_id(avainsana_id);
        }
    }

    @Override
    public int getInfra_id() {
        return _infra_id;
    }

    @Override
    public void setInfra_id(int infra_id) {
        _infra_id = infra_id;
    }

    @Override
    public int getAvainsana_id() {
        return _avainsana_id;
    }

    @Override
    public void setAvainsana_id(int avainsana_id) {
        _avainsana_id = avainsana_id;
    }

    @Override
    public Infra_Avainsanat toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Infra_Avainsanat) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        Infra_AvainsanatImpl infra_AvainsanatImpl = new Infra_AvainsanatImpl();

        infra_AvainsanatImpl.setInfra_id(getInfra_id());
        infra_AvainsanatImpl.setAvainsana_id(getAvainsana_id());

        infra_AvainsanatImpl.resetOriginalValues();

        return infra_AvainsanatImpl;
    }

    @Override
    public int compareTo(Infra_Avainsanat infra_Avainsanat) {
        Infra_AvainsanatPK primaryKey = infra_Avainsanat.getPrimaryKey();

        return getPrimaryKey().compareTo(primaryKey);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Infra_Avainsanat)) {
            return false;
        }

        Infra_Avainsanat infra_Avainsanat = (Infra_Avainsanat) obj;

        Infra_AvainsanatPK primaryKey = infra_Avainsanat.getPrimaryKey();

        if (getPrimaryKey().equals(primaryKey)) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey().hashCode();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Infra_Avainsanat> toCacheModel() {
        Infra_AvainsanatCacheModel infra_AvainsanatCacheModel = new Infra_AvainsanatCacheModel();

        infra_AvainsanatCacheModel.infra_id = getInfra_id();

        infra_AvainsanatCacheModel.avainsana_id = getAvainsana_id();

        return infra_AvainsanatCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(5);

        sb.append("{infra_id=");
        sb.append(getInfra_id());
        sb.append(", avainsana_id=");
        sb.append(getAvainsana_id());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(10);

        sb.append("<model><model-name>");
        sb.append("fi.csc.avaa.tupa.db.model.Infra_Avainsanat");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>infra_id</column-name><column-value><![CDATA[");
        sb.append(getInfra_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>avainsana_id</column-name><column-value><![CDATA[");
        sb.append(getAvainsana_id());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
