package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.Infra_Avainsanat;
import fi.csc.avaa.tupa.db.service.Infra_AvainsanatLocalServiceUtil;

/**
 * The extended model base implementation for the Infra_Avainsanat service. Represents a row in the &quot;infra_avainsanat&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Infra_AvainsanatImpl}.
 * </p>
 *
 * @author CSC
 * @see Infra_AvainsanatImpl
 * @see fi.csc.avaa.tupa.db.model.Infra_Avainsanat
 * @generated
 */
public abstract class Infra_AvainsanatBaseImpl extends Infra_AvainsanatModelImpl
    implements Infra_Avainsanat {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a infra_ avainsanat model instance should use the {@link Infra_Avainsanat} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Infra_AvainsanatLocalServiceUtil.addInfra_Avainsanat(this);
        } else {
            Infra_AvainsanatLocalServiceUtil.updateInfra_Avainsanat(this);
        }
    }
}
