package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import fi.csc.avaa.tupa.db.model.Kayttoehto;
import fi.csc.avaa.tupa.db.model.KayttoehtoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Kayttoehto service. Represents a row in the &quot;kayttoehto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link fi.csc.avaa.tupa.db.model.KayttoehtoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KayttoehtoImpl}.
 * </p>
 *
 * @author CSC
 * @see KayttoehtoImpl
 * @see fi.csc.avaa.tupa.db.model.Kayttoehto
 * @see fi.csc.avaa.tupa.db.model.KayttoehtoModel
 * @generated
 */
public class KayttoehtoModelImpl extends BaseModelImpl<Kayttoehto>
    implements KayttoehtoModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a kayttoehto model instance should use the {@link fi.csc.avaa.tupa.db.model.Kayttoehto} interface instead.
     */
    public static final String TABLE_NAME = "kayttoehto";
    public static final Object[][] TABLE_COLUMNS = {
            { "infra_id", Types.INTEGER },
            { "saavutettavuus", Types.INTEGER },
            { "anonymiteetti", Types.INTEGER },
            { "maksullisuus", Types.INTEGER },
            { "tulosten_julkaisuvelvoite", Types.INTEGER },
            { "tuotoksien_julkaisuvelvoite", Types.INTEGER },
            { "osaamisen_avoimuus", Types.INTEGER },
            { "seurantatyokalut", Types.INTEGER },
            { "tulosten_lisensointi", Types.INTEGER },
            { "URLfi", Types.VARCHAR },
            { "URLen", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table kayttoehto (infra_id INTEGER not null primary key,saavutettavuus INTEGER,anonymiteetti INTEGER,maksullisuus INTEGER,tulosten_julkaisuvelvoite INTEGER,tuotoksien_julkaisuvelvoite INTEGER,osaamisen_avoimuus INTEGER,seurantatyokalut INTEGER,tulosten_lisensointi INTEGER,URLfi VARCHAR(75) null,URLen VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table kayttoehto";
    public static final String ORDER_BY_JPQL = " ORDER BY kayttoehto.infra_id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY kayttoehto.infra_id ASC";
    public static final String DATA_SOURCE = "tupa";
    public static final String SESSION_FACTORY = "tupaSessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.fi.csc.avaa.tupa.db.model.Kayttoehto"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.fi.csc.avaa.tupa.db.model.Kayttoehto"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.fi.csc.avaa.tupa.db.model.Kayttoehto"));
    private static ClassLoader _classLoader = Kayttoehto.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Kayttoehto.class
        };
    private int _infra_id;
    private int _saavutettavuus;
    private int _anonymiteetti;
    private int _maksullisuus;
    private int _tulosten_julkaisuvelvoite;
    private int _tuotoksien_julkaisuvelvoite;
    private int _osaamisen_avoimuus;
    private int _seurantatyokalut;
    private int _tulosten_lisensointi;
    private String _URLfi;
    private String _URLen;
    private Kayttoehto _escapedModel;

    public KayttoehtoModelImpl() {
    }

    @Override
    public int getPrimaryKey() {
        return _infra_id;
    }

    @Override
    public void setPrimaryKey(int primaryKey) {
        setInfra_id(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _infra_id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Integer) primaryKeyObj).intValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Kayttoehto.class;
    }

    @Override
    public String getModelClassName() {
        return Kayttoehto.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("infra_id", getInfra_id());
        attributes.put("saavutettavuus", getSaavutettavuus());
        attributes.put("anonymiteetti", getAnonymiteetti());
        attributes.put("maksullisuus", getMaksullisuus());
        attributes.put("tulosten_julkaisuvelvoite",
            getTulosten_julkaisuvelvoite());
        attributes.put("tuotoksien_julkaisuvelvoite",
            getTuotoksien_julkaisuvelvoite());
        attributes.put("osaamisen_avoimuus", getOsaamisen_avoimuus());
        attributes.put("seurantatyokalut", getSeurantatyokalut());
        attributes.put("tulosten_lisensointi", getTulosten_lisensointi());
        attributes.put("URLfi", getURLfi());
        attributes.put("URLen", getURLen());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer infra_id = (Integer) attributes.get("infra_id");

        if (infra_id != null) {
            setInfra_id(infra_id);
        }

        Integer saavutettavuus = (Integer) attributes.get("saavutettavuus");

        if (saavutettavuus != null) {
            setSaavutettavuus(saavutettavuus);
        }

        Integer anonymiteetti = (Integer) attributes.get("anonymiteetti");

        if (anonymiteetti != null) {
            setAnonymiteetti(anonymiteetti);
        }

        Integer maksullisuus = (Integer) attributes.get("maksullisuus");

        if (maksullisuus != null) {
            setMaksullisuus(maksullisuus);
        }

        Integer tulosten_julkaisuvelvoite = (Integer) attributes.get(
                "tulosten_julkaisuvelvoite");

        if (tulosten_julkaisuvelvoite != null) {
            setTulosten_julkaisuvelvoite(tulosten_julkaisuvelvoite);
        }

        Integer tuotoksien_julkaisuvelvoite = (Integer) attributes.get(
                "tuotoksien_julkaisuvelvoite");

        if (tuotoksien_julkaisuvelvoite != null) {
            setTuotoksien_julkaisuvelvoite(tuotoksien_julkaisuvelvoite);
        }

        Integer osaamisen_avoimuus = (Integer) attributes.get(
                "osaamisen_avoimuus");

        if (osaamisen_avoimuus != null) {
            setOsaamisen_avoimuus(osaamisen_avoimuus);
        }

        Integer seurantatyokalut = (Integer) attributes.get("seurantatyokalut");

        if (seurantatyokalut != null) {
            setSeurantatyokalut(seurantatyokalut);
        }

        Integer tulosten_lisensointi = (Integer) attributes.get(
                "tulosten_lisensointi");

        if (tulosten_lisensointi != null) {
            setTulosten_lisensointi(tulosten_lisensointi);
        }

        String URLfi = (String) attributes.get("URLfi");

        if (URLfi != null) {
            setURLfi(URLfi);
        }

        String URLen = (String) attributes.get("URLen");

        if (URLen != null) {
            setURLen(URLen);
        }
    }

    @Override
    public int getInfra_id() {
        return _infra_id;
    }

    @Override
    public void setInfra_id(int infra_id) {
        _infra_id = infra_id;
    }

    @Override
    public int getSaavutettavuus() {
        return _saavutettavuus;
    }

    @Override
    public void setSaavutettavuus(int saavutettavuus) {
        _saavutettavuus = saavutettavuus;
    }

    @Override
    public int getAnonymiteetti() {
        return _anonymiteetti;
    }

    @Override
    public void setAnonymiteetti(int anonymiteetti) {
        _anonymiteetti = anonymiteetti;
    }

    @Override
    public int getMaksullisuus() {
        return _maksullisuus;
    }

    @Override
    public void setMaksullisuus(int maksullisuus) {
        _maksullisuus = maksullisuus;
    }

    @Override
    public int getTulosten_julkaisuvelvoite() {
        return _tulosten_julkaisuvelvoite;
    }

    @Override
    public void setTulosten_julkaisuvelvoite(int tulosten_julkaisuvelvoite) {
        _tulosten_julkaisuvelvoite = tulosten_julkaisuvelvoite;
    }

    @Override
    public int getTuotoksien_julkaisuvelvoite() {
        return _tuotoksien_julkaisuvelvoite;
    }

    @Override
    public void setTuotoksien_julkaisuvelvoite(int tuotoksien_julkaisuvelvoite) {
        _tuotoksien_julkaisuvelvoite = tuotoksien_julkaisuvelvoite;
    }

    @Override
    public int getOsaamisen_avoimuus() {
        return _osaamisen_avoimuus;
    }

    @Override
    public void setOsaamisen_avoimuus(int osaamisen_avoimuus) {
        _osaamisen_avoimuus = osaamisen_avoimuus;
    }

    @Override
    public int getSeurantatyokalut() {
        return _seurantatyokalut;
    }

    @Override
    public void setSeurantatyokalut(int seurantatyokalut) {
        _seurantatyokalut = seurantatyokalut;
    }

    @Override
    public int getTulosten_lisensointi() {
        return _tulosten_lisensointi;
    }

    @Override
    public void setTulosten_lisensointi(int tulosten_lisensointi) {
        _tulosten_lisensointi = tulosten_lisensointi;
    }

    @Override
    public String getURLfi() {
        if (_URLfi == null) {
            return StringPool.BLANK;
        } else {
            return _URLfi;
        }
    }

    @Override
    public void setURLfi(String URLfi) {
        _URLfi = URLfi;
    }

    @Override
    public String getURLen() {
        if (_URLen == null) {
            return StringPool.BLANK;
        } else {
            return _URLen;
        }
    }

    @Override
    public void setURLen(String URLen) {
        _URLen = URLen;
    }

    @Override
    public Kayttoehto toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Kayttoehto) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        KayttoehtoImpl kayttoehtoImpl = new KayttoehtoImpl();

        kayttoehtoImpl.setInfra_id(getInfra_id());
        kayttoehtoImpl.setSaavutettavuus(getSaavutettavuus());
        kayttoehtoImpl.setAnonymiteetti(getAnonymiteetti());
        kayttoehtoImpl.setMaksullisuus(getMaksullisuus());
        kayttoehtoImpl.setTulosten_julkaisuvelvoite(getTulosten_julkaisuvelvoite());
        kayttoehtoImpl.setTuotoksien_julkaisuvelvoite(getTuotoksien_julkaisuvelvoite());
        kayttoehtoImpl.setOsaamisen_avoimuus(getOsaamisen_avoimuus());
        kayttoehtoImpl.setSeurantatyokalut(getSeurantatyokalut());
        kayttoehtoImpl.setTulosten_lisensointi(getTulosten_lisensointi());
        kayttoehtoImpl.setURLfi(getURLfi());
        kayttoehtoImpl.setURLen(getURLen());

        kayttoehtoImpl.resetOriginalValues();

        return kayttoehtoImpl;
    }

    @Override
    public int compareTo(Kayttoehto kayttoehto) {
        int primaryKey = kayttoehto.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Kayttoehto)) {
            return false;
        }

        Kayttoehto kayttoehto = (Kayttoehto) obj;

        int primaryKey = kayttoehto.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Kayttoehto> toCacheModel() {
        KayttoehtoCacheModel kayttoehtoCacheModel = new KayttoehtoCacheModel();

        kayttoehtoCacheModel.infra_id = getInfra_id();

        kayttoehtoCacheModel.saavutettavuus = getSaavutettavuus();

        kayttoehtoCacheModel.anonymiteetti = getAnonymiteetti();

        kayttoehtoCacheModel.maksullisuus = getMaksullisuus();

        kayttoehtoCacheModel.tulosten_julkaisuvelvoite = getTulosten_julkaisuvelvoite();

        kayttoehtoCacheModel.tuotoksien_julkaisuvelvoite = getTuotoksien_julkaisuvelvoite();

        kayttoehtoCacheModel.osaamisen_avoimuus = getOsaamisen_avoimuus();

        kayttoehtoCacheModel.seurantatyokalut = getSeurantatyokalut();

        kayttoehtoCacheModel.tulosten_lisensointi = getTulosten_lisensointi();

        kayttoehtoCacheModel.URLfi = getURLfi();

        String URLfi = kayttoehtoCacheModel.URLfi;

        if ((URLfi != null) && (URLfi.length() == 0)) {
            kayttoehtoCacheModel.URLfi = null;
        }

        kayttoehtoCacheModel.URLen = getURLen();

        String URLen = kayttoehtoCacheModel.URLen;

        if ((URLen != null) && (URLen.length() == 0)) {
            kayttoehtoCacheModel.URLen = null;
        }

        return kayttoehtoCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(23);

        sb.append("{infra_id=");
        sb.append(getInfra_id());
        sb.append(", saavutettavuus=");
        sb.append(getSaavutettavuus());
        sb.append(", anonymiteetti=");
        sb.append(getAnonymiteetti());
        sb.append(", maksullisuus=");
        sb.append(getMaksullisuus());
        sb.append(", tulosten_julkaisuvelvoite=");
        sb.append(getTulosten_julkaisuvelvoite());
        sb.append(", tuotoksien_julkaisuvelvoite=");
        sb.append(getTuotoksien_julkaisuvelvoite());
        sb.append(", osaamisen_avoimuus=");
        sb.append(getOsaamisen_avoimuus());
        sb.append(", seurantatyokalut=");
        sb.append(getSeurantatyokalut());
        sb.append(", tulosten_lisensointi=");
        sb.append(getTulosten_lisensointi());
        sb.append(", URLfi=");
        sb.append(getURLfi());
        sb.append(", URLen=");
        sb.append(getURLen());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(37);

        sb.append("<model><model-name>");
        sb.append("fi.csc.avaa.tupa.db.model.Kayttoehto");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>infra_id</column-name><column-value><![CDATA[");
        sb.append(getInfra_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>saavutettavuus</column-name><column-value><![CDATA[");
        sb.append(getSaavutettavuus());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>anonymiteetti</column-name><column-value><![CDATA[");
        sb.append(getAnonymiteetti());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>maksullisuus</column-name><column-value><![CDATA[");
        sb.append(getMaksullisuus());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>tulosten_julkaisuvelvoite</column-name><column-value><![CDATA[");
        sb.append(getTulosten_julkaisuvelvoite());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>tuotoksien_julkaisuvelvoite</column-name><column-value><![CDATA[");
        sb.append(getTuotoksien_julkaisuvelvoite());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>osaamisen_avoimuus</column-name><column-value><![CDATA[");
        sb.append(getOsaamisen_avoimuus());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>seurantatyokalut</column-name><column-value><![CDATA[");
        sb.append(getSeurantatyokalut());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>tulosten_lisensointi</column-name><column-value><![CDATA[");
        sb.append(getTulosten_lisensointi());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>URLfi</column-name><column-value><![CDATA[");
        sb.append(getURLfi());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>URLen</column-name><column-value><![CDATA[");
        sb.append(getURLen());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
