package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.Organisaatio;
import fi.csc.avaa.tupa.db.service.OrganisaatioLocalServiceUtil;

/**
 * The extended model base implementation for the Organisaatio service. Represents a row in the &quot;organisaatio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OrganisaatioImpl}.
 * </p>
 *
 * @author CSC
 * @see OrganisaatioImpl
 * @see fi.csc.avaa.tupa.db.model.Organisaatio
 * @generated
 */
public abstract class OrganisaatioBaseImpl extends OrganisaatioModelImpl
    implements Organisaatio {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a organisaatio model instance should use the {@link Organisaatio} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            OrganisaatioLocalServiceUtil.addOrganisaatio(this);
        } else {
            OrganisaatioLocalServiceUtil.updateOrganisaatio(this);
        }
    }
}
