package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.Selite;
import fi.csc.avaa.tupa.db.service.SeliteLocalServiceUtil;

/**
 * The extended model base implementation for the Selite service. Represents a row in the &quot;selite&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SeliteImpl}.
 * </p>
 *
 * @author CSC
 * @see SeliteImpl
 * @see fi.csc.avaa.tupa.db.model.Selite
 * @generated
 */
public abstract class SeliteBaseImpl extends SeliteModelImpl implements Selite {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a selite model instance should use the {@link Selite} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SeliteLocalServiceUtil.addSelite(this);
        } else {
            SeliteLocalServiceUtil.updateSelite(this);
        }
    }
}
