package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.TpContact;
import fi.csc.avaa.tupa.db.service.TpContactLocalServiceUtil;

/**
 * The extended model base implementation for the TpContact service. Represents a row in the &quot;tupa_TpContact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TpContactImpl}.
 * </p>
 *
 * @author CSC
 * @see TpContactImpl
 * @see fi.csc.avaa.tupa.db.model.TpContact
 * @generated
 */
public abstract class TpContactBaseImpl extends TpContactModelImpl
    implements TpContact {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a tp contact model instance should use the {@link TpContact} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TpContactLocalServiceUtil.addTpContact(this);
        } else {
            TpContactLocalServiceUtil.updateTpContact(this);
        }
    }
}
