package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.TpInfrastructure;
import fi.csc.avaa.tupa.db.service.TpInfrastructureLocalServiceUtil;

/**
 * The extended model base implementation for the TpInfrastructure service. Represents a row in the &quot;tupa_TpInfrastructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TpInfrastructureImpl}.
 * </p>
 *
 * @author CSC
 * @see TpInfrastructureImpl
 * @see fi.csc.avaa.tupa.db.model.TpInfrastructure
 * @generated
 */
public abstract class TpInfrastructureBaseImpl extends TpInfrastructureModelImpl
    implements TpInfrastructure {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a tp infrastructure model instance should use the {@link TpInfrastructure} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TpInfrastructureLocalServiceUtil.addTpInfrastructure(this);
        } else {
            TpInfrastructureLocalServiceUtil.updateTpInfrastructure(this);
        }
    }
}
