package fi.csc.avaa.tupa.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.tupa.db.model.TpOrganisation;
import fi.csc.avaa.tupa.db.service.TpOrganisationLocalServiceUtil;

/**
 * The extended model base implementation for the TpOrganisation service. Represents a row in the &quot;tupa_TpOrganisation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TpOrganisationImpl}.
 * </p>
 *
 * @author CSC
 * @see TpOrganisationImpl
 * @see fi.csc.avaa.tupa.db.model.TpOrganisation
 * @generated
 */
public abstract class TpOrganisationBaseImpl extends TpOrganisationModelImpl
    implements TpOrganisation {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a tp organisation model instance should use the {@link TpOrganisation} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TpOrganisationLocalServiceUtil.addTpOrganisation(this);
        } else {
            TpOrganisationLocalServiceUtil.updateTpOrganisation(this);
        }
    }
}
