package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Avainsana service. Represents a row in the &quot;avainsana&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.AvainsanaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.AvainsanaImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see Avainsana
 * @see fi.csc.avaa.tupa.db.model.impl.AvainsanaImpl
 * @see fi.csc.avaa.tupa.db.model.impl.AvainsanaModelImpl
 * @generated
 */
public interface AvainsanaModel extends BaseModel<Avainsana> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a avainsana model instance should use the {@link Avainsana} interface instead.
     */

    /**
     * Returns the primary key of this avainsana.
     *
     * @return the primary key of this avainsana
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this avainsana.
     *
     * @param primaryKey the primary key of this avainsana
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the avainsana_id of this avainsana.
     *
     * @return the avainsana_id of this avainsana
     */
    public int getAvainsana_id();

    /**
     * Sets the avainsana_id of this avainsana.
     *
     * @param avainsana_id the avainsana_id of this avainsana
     */
    public void setAvainsana_id(int avainsana_id);

    /**
     * Returns the avainsana of this avainsana.
     *
     * @return the avainsana of this avainsana
     */
    @AutoEscape
    public String getAvainsana();

    /**
     * Sets the avainsana of this avainsana.
     *
     * @param avainsana the avainsana of this avainsana
     */
    public void setAvainsana(String avainsana);

    /**
     * Returns the keyword of this avainsana.
     *
     * @return the keyword of this avainsana
     */
    @AutoEscape
    public String getKeyword();

    /**
     * Sets the keyword of this avainsana.
     *
     * @param keyword the keyword of this avainsana
     */
    public void setKeyword(String keyword);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Avainsana avainsana);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Avainsana> toCacheModel();

    @Override
    public Avainsana toEscapedModel();

    @Override
    public Avainsana toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
