package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import fi.csc.avaa.tupa.db.service.persistence.Infra_AvainsanatPK;

import java.io.Serializable;

/**
 * The base model interface for the Infra_Avainsanat service. Represents a row in the &quot;infra_avainsanat&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.Infra_AvainsanatModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.Infra_AvainsanatImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see Infra_Avainsanat
 * @see fi.csc.avaa.tupa.db.model.impl.Infra_AvainsanatImpl
 * @see fi.csc.avaa.tupa.db.model.impl.Infra_AvainsanatModelImpl
 * @generated
 */
public interface Infra_AvainsanatModel extends BaseModel<Infra_Avainsanat> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a infra_ avainsanat model instance should use the {@link Infra_Avainsanat} interface instead.
     */

    /**
     * Returns the primary key of this infra_ avainsanat.
     *
     * @return the primary key of this infra_ avainsanat
     */
    public Infra_AvainsanatPK getPrimaryKey();

    /**
     * Sets the primary key of this infra_ avainsanat.
     *
     * @param primaryKey the primary key of this infra_ avainsanat
     */
    public void setPrimaryKey(Infra_AvainsanatPK primaryKey);

    /**
     * Returns the infra_id of this infra_ avainsanat.
     *
     * @return the infra_id of this infra_ avainsanat
     */
    public int getInfra_id();

    /**
     * Sets the infra_id of this infra_ avainsanat.
     *
     * @param infra_id the infra_id of this infra_ avainsanat
     */
    public void setInfra_id(int infra_id);

    /**
     * Returns the avainsana_id of this infra_ avainsanat.
     *
     * @return the avainsana_id of this infra_ avainsanat
     */
    public int getAvainsana_id();

    /**
     * Sets the avainsana_id of this infra_ avainsanat.
     *
     * @param avainsana_id the avainsana_id of this infra_ avainsanat
     */
    public void setAvainsana_id(int avainsana_id);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Infra_Avainsanat infra_Avainsanat);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Infra_Avainsanat> toCacheModel();

    @Override
    public Infra_Avainsanat toEscapedModel();

    @Override
    public Infra_Avainsanat toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
