package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Infra service. Represents a row in the &quot;infra&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.InfraModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.InfraImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see Infra
 * @see fi.csc.avaa.tupa.db.model.impl.InfraImpl
 * @see fi.csc.avaa.tupa.db.model.impl.InfraModelImpl
 * @generated
 */
public interface InfraModel extends BaseModel<Infra> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a infra model instance should use the {@link Infra} interface instead.
     */

    /**
     * Returns the primary key of this infra.
     *
     * @return the primary key of this infra
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this infra.
     *
     * @param primaryKey the primary key of this infra
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the infra_id of this infra.
     *
     * @return the infra_id of this infra
     */
    public int getInfra_id();

    /**
     * Sets the infra_id of this infra.
     *
     * @param infra_id the infra_id of this infra
     */
    public void setInfra_id(int infra_id);

    /**
     * Returns the i s n i of this infra.
     *
     * @return the i s n i of this infra
     */
    @AutoEscape
    public String getISNI();

    /**
     * Sets the i s n i of this infra.
     *
     * @param ISNI the i s n i of this infra
     */
    public void setISNI(String ISNI);

    /**
     * Returns the aktiivinen of this infra.
     *
     * @return the aktiivinen of this infra
     */
    public boolean getAktiivinen();

    /**
     * Returns <code>true</code> if this infra is aktiivinen.
     *
     * @return <code>true</code> if this infra is aktiivinen; <code>false</code> otherwise
     */
    public boolean isAktiivinen();

    /**
     * Sets whether this infra is aktiivinen.
     *
     * @param aktiivinen the aktiivinen of this infra
     */
    public void setAktiivinen(boolean aktiivinen);

    /**
     * Returns the valmistelu_aloitusvuosi of this infra.
     *
     * @return the valmistelu_aloitusvuosi of this infra
     */
    public int getValmistelu_aloitusvuosi();

    /**
     * Sets the valmistelu_aloitusvuosi of this infra.
     *
     * @param valmistelu_aloitusvuosi the valmistelu_aloitusvuosi of this infra
     */
    public void setValmistelu_aloitusvuosi(int valmistelu_aloitusvuosi);

    /**
     * Returns the rakennus_aloitusvuosi of this infra.
     *
     * @return the rakennus_aloitusvuosi of this infra
     */
    public int getRakennus_aloitusvuosi();

    /**
     * Sets the rakennus_aloitusvuosi of this infra.
     *
     * @param rakennus_aloitusvuosi the rakennus_aloitusvuosi of this infra
     */
    public void setRakennus_aloitusvuosi(int rakennus_aloitusvuosi);

    /**
     * Returns the toiminta_aloitusvuosi of this infra.
     *
     * @return the toiminta_aloitusvuosi of this infra
     */
    public int getToiminta_aloitusvuosi();

    /**
     * Sets the toiminta_aloitusvuosi of this infra.
     *
     * @param toiminta_aloitusvuosi the toiminta_aloitusvuosi of this infra
     */
    public void setToiminta_aloitusvuosi(int toiminta_aloitusvuosi);

    /**
     * Returns the toiminta_lopetusvuosi of this infra.
     *
     * @return the toiminta_lopetusvuosi of this infra
     */
    public int getToiminta_lopetusvuosi();

    /**
     * Sets the toiminta_lopetusvuosi of this infra.
     *
     * @param toiminta_lopetusvuosi the toiminta_lopetusvuosi of this infra
     */
    public void setToiminta_lopetusvuosi(int toiminta_lopetusvuosi);

    /**
     * Returns the nimi of this infra.
     *
     * @return the nimi of this infra
     */
    @AutoEscape
    public String getNimi();

    /**
     * Sets the nimi of this infra.
     *
     * @param nimi the nimi of this infra
     */
    public void setNimi(String nimi);

    /**
     * Returns the name of this infra.
     *
     * @return the name of this infra
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this infra.
     *
     * @param name the name of this infra
     */
    public void setName(String name);

    /**
     * Returns the lyhenne of this infra.
     *
     * @return the lyhenne of this infra
     */
    @AutoEscape
    public String getLyhenne();

    /**
     * Sets the lyhenne of this infra.
     *
     * @param lyhenne the lyhenne of this infra
     */
    public void setLyhenne(String lyhenne);

    /**
     * Returns the acronym of this infra.
     *
     * @return the acronym of this infra
     */
    @AutoEscape
    public String getAcronym();

    /**
     * Sets the acronym of this infra.
     *
     * @param acronym the acronym of this infra
     */
    public void setAcronym(String acronym);

    /**
     * Returns the edellinen_infra of this infra.
     *
     * @return the edellinen_infra of this infra
     */
    public int getEdellinen_infra();

    /**
     * Sets the edellinen_infra of this infra.
     *
     * @param edellinen_infra the edellinen_infra of this infra
     */
    public void setEdellinen_infra(int edellinen_infra);

    /**
     * Returns the kuvaus of this infra.
     *
     * @return the kuvaus of this infra
     */
    @AutoEscape
    public String getKuvaus();

    /**
     * Sets the kuvaus of this infra.
     *
     * @param kuvaus the kuvaus of this infra
     */
    public void setKuvaus(String kuvaus);

    /**
     * Returns the description of this infra.
     *
     * @return the description of this infra
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this infra.
     *
     * @param description the description of this infra
     */
    public void setDescription(String description);

    /**
     * Returns the logo_url of this infra.
     *
     * @return the logo_url of this infra
     */
    @AutoEscape
    public String getLogo_url();

    /**
     * Sets the logo_url of this infra.
     *
     * @param logo_url the logo_url of this infra
     */
    public void setLogo_url(String logo_url);

    /**
     * Returns the image_url of this infra.
     *
     * @return the image_url of this infra
     */
    @AutoEscape
    public String getImage_url();

    /**
     * Sets the image_url of this infra.
     *
     * @param image_url the image_url of this infra
     */
    public void setImage_url(String image_url);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Infra infra);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Infra> toCacheModel();

    @Override
    public Infra toEscapedModel();

    @Override
    public Infra toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
