package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Organisaatio service. Represents a row in the &quot;organisaatio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.OrganisaatioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.OrganisaatioImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see Organisaatio
 * @see fi.csc.avaa.tupa.db.model.impl.OrganisaatioImpl
 * @see fi.csc.avaa.tupa.db.model.impl.OrganisaatioModelImpl
 * @generated
 */
public interface OrganisaatioModel extends BaseModel<Organisaatio> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a organisaatio model instance should use the {@link Organisaatio} interface instead.
     */

    /**
     * Returns the primary key of this organisaatio.
     *
     * @return the primary key of this organisaatio
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this organisaatio.
     *
     * @param primaryKey the primary key of this organisaatio
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the organisaatio_id of this organisaatio.
     *
     * @return the organisaatio_id of this organisaatio
     */
    public int getOrganisaatio_id();

    /**
     * Sets the organisaatio_id of this organisaatio.
     *
     * @param organisaatio_id the organisaatio_id of this organisaatio
     */
    public void setOrganisaatio_id(int organisaatio_id);

    /**
     * Returns the nimi of this organisaatio.
     *
     * @return the nimi of this organisaatio
     */
    @AutoEscape
    public String getNimi();

    /**
     * Sets the nimi of this organisaatio.
     *
     * @param nimi the nimi of this organisaatio
     */
    public void setNimi(String nimi);

    /**
     * Returns the name of this organisaatio.
     *
     * @return the name of this organisaatio
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this organisaatio.
     *
     * @param name the name of this organisaatio
     */
    public void setName(String name);

    /**
     * Returns the maa of this organisaatio.
     *
     * @return the maa of this organisaatio
     */
    @AutoEscape
    public String getMaa();

    /**
     * Sets the maa of this organisaatio.
     *
     * @param maa the maa of this organisaatio
     */
    public void setMaa(String maa);

    /**
     * Returns the i s n i of this organisaatio.
     *
     * @return the i s n i of this organisaatio
     */
    @AutoEscape
    public String getISNI();

    /**
     * Sets the i s n i of this organisaatio.
     *
     * @param ISNI the i s n i of this organisaatio
     */
    public void setISNI(String ISNI);

    /**
     * Returns the crmid of this organisaatio.
     *
     * @return the crmid of this organisaatio
     */
    @AutoEscape
    public String getCrmid();

    /**
     * Sets the crmid of this organisaatio.
     *
     * @param crmid the crmid of this organisaatio
     */
    public void setCrmid(String crmid);

    /**
     * Returns the emo_organisaatio of this organisaatio.
     *
     * @return the emo_organisaatio of this organisaatio
     */
    public int getEmo_organisaatio();

    /**
     * Sets the emo_organisaatio of this organisaatio.
     *
     * @param emo_organisaatio the emo_organisaatio of this organisaatio
     */
    public void setEmo_organisaatio(int emo_organisaatio);

    /**
     * Returns the kv_isanta of this organisaatio.
     *
     * @return the kv_isanta of this organisaatio
     */
    public boolean getKv_isanta();

    /**
     * Returns <code>true</code> if this organisaatio is kv_isanta.
     *
     * @return <code>true</code> if this organisaatio is kv_isanta; <code>false</code> otherwise
     */
    public boolean isKv_isanta();

    /**
     * Sets whether this organisaatio is kv_isanta.
     *
     * @param kv_isanta the kv_isanta of this organisaatio
     */
    public void setKv_isanta(boolean kv_isanta);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Organisaatio organisaatio);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Organisaatio> toCacheModel();

    @Override
    public Organisaatio toEscapedModel();

    @Override
    public Organisaatio toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
