package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Palvelu service. Represents a row in the &quot;palvelu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.PalveluModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.PalveluImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see Palvelu
 * @see fi.csc.avaa.tupa.db.model.impl.PalveluImpl
 * @see fi.csc.avaa.tupa.db.model.impl.PalveluModelImpl
 * @generated
 */
public interface PalveluModel extends BaseModel<Palvelu> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a palvelu model instance should use the {@link Palvelu} interface instead.
     */

    /**
     * Returns the primary key of this palvelu.
     *
     * @return the primary key of this palvelu
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this palvelu.
     *
     * @param primaryKey the primary key of this palvelu
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the palvelu_id of this palvelu.
     *
     * @return the palvelu_id of this palvelu
     */
    public int getPalvelu_id();

    /**
     * Sets the palvelu_id of this palvelu.
     *
     * @param palvelu_id the palvelu_id of this palvelu
     */
    public void setPalvelu_id(int palvelu_id);

    /**
     * Returns the nimi of this palvelu.
     *
     * @return the nimi of this palvelu
     */
    @AutoEscape
    public String getNimi();

    /**
     * Sets the nimi of this palvelu.
     *
     * @param nimi the nimi of this palvelu
     */
    public void setNimi(String nimi);

    /**
     * Returns the name of this palvelu.
     *
     * @return the name of this palvelu
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this palvelu.
     *
     * @param name the name of this palvelu
     */
    public void setName(String name);

    /**
     * Returns the kuvaus of this palvelu.
     *
     * @return the kuvaus of this palvelu
     */
    @AutoEscape
    public String getKuvaus();

    /**
     * Sets the kuvaus of this palvelu.
     *
     * @param kuvaus the kuvaus of this palvelu
     */
    public void setKuvaus(String kuvaus);

    /**
     * Returns the description of this palvelu.
     *
     * @return the description of this palvelu
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this palvelu.
     *
     * @param description the description of this palvelu
     */
    public void setDescription(String description);

    /**
     * Returns the u r len of this palvelu.
     *
     * @return the u r len of this palvelu
     */
    @AutoEscape
    public String getURLen();

    /**
     * Sets the u r len of this palvelu.
     *
     * @param URLen the u r len of this palvelu
     */
    public void setURLen(String URLen);

    /**
     * Returns the u r lfi of this palvelu.
     *
     * @return the u r lfi of this palvelu
     */
    @AutoEscape
    public String getURLfi();

    /**
     * Sets the u r lfi of this palvelu.
     *
     * @param URLfi the u r lfi of this palvelu
     */
    public void setURLfi(String URLfi);

    /**
     * Returns the paikkatyyppi of this palvelu.
     *
     * @return the paikkatyyppi of this palvelu
     */
    public int getPaikkatyyppi();

    /**
     * Sets the paikkatyyppi of this palvelu.
     *
     * @param paikkatyyppi the paikkatyyppi of this palvelu
     */
    public void setPaikkatyyppi(int paikkatyyppi);

    /**
     * Returns the katuosoite of this palvelu.
     *
     * @return the katuosoite of this palvelu
     */
    @AutoEscape
    public String getKatuosoite();

    /**
     * Sets the katuosoite of this palvelu.
     *
     * @param katuosoite the katuosoite of this palvelu
     */
    public void setKatuosoite(String katuosoite);

    /**
     * Returns the kaupunki of this palvelu.
     *
     * @return the kaupunki of this palvelu
     */
    @AutoEscape
    public String getKaupunki();

    /**
     * Sets the kaupunki of this palvelu.
     *
     * @param kaupunki the kaupunki of this palvelu
     */
    public void setKaupunki(String kaupunki);

    /**
     * Returns the lat of this palvelu.
     *
     * @return the lat of this palvelu
     */
    public double getLat();

    /**
     * Sets the lat of this palvelu.
     *
     * @param lat the lat of this palvelu
     */
    public void setLat(double lat);

    /**
     * Returns the lon of this palvelu.
     *
     * @return the lon of this palvelu
     */
    public double getLon();

    /**
     * Sets the lon of this palvelu.
     *
     * @param lon the lon of this palvelu
     */
    public void setLon(double lon);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Palvelu palvelu);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Palvelu> toCacheModel();

    @Override
    public Palvelu toEscapedModel();

    @Override
    public Palvelu toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
