package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Palvelutyyppi service. Represents a row in the &quot;palvelutyyppi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.PalvelutyyppiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.PalvelutyyppiImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see Palvelutyyppi
 * @see fi.csc.avaa.tupa.db.model.impl.PalvelutyyppiImpl
 * @see fi.csc.avaa.tupa.db.model.impl.PalvelutyyppiModelImpl
 * @generated
 */
public interface PalvelutyyppiModel extends BaseModel<Palvelutyyppi> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a palvelutyyppi model instance should use the {@link Palvelutyyppi} interface instead.
     */

    /**
     * Returns the primary key of this palvelutyyppi.
     *
     * @return the primary key of this palvelutyyppi
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this palvelutyyppi.
     *
     * @param primaryKey the primary key of this palvelutyyppi
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the palvelutyyppi_id of this palvelutyyppi.
     *
     * @return the palvelutyyppi_id of this palvelutyyppi
     */
    public int getPalvelutyyppi_id();

    /**
     * Sets the palvelutyyppi_id of this palvelutyyppi.
     *
     * @param palvelutyyppi_id the palvelutyyppi_id of this palvelutyyppi
     */
    public void setPalvelutyyppi_id(int palvelutyyppi_id);

    /**
     * Returns the tyyppi of this palvelutyyppi.
     *
     * @return the tyyppi of this palvelutyyppi
     */
    public int getTyyppi();

    /**
     * Sets the tyyppi of this palvelutyyppi.
     *
     * @param tyyppi the tyyppi of this palvelutyyppi
     */
    public void setTyyppi(int tyyppi);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Palvelutyyppi palvelutyyppi);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Palvelutyyppi> toCacheModel();

    @Override
    public Palvelutyyppi toEscapedModel();

    @Override
    public Palvelutyyppi toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
