package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Selite service. Represents a row in the &quot;selite&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.SeliteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.SeliteImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see Selite
 * @see fi.csc.avaa.tupa.db.model.impl.SeliteImpl
 * @see fi.csc.avaa.tupa.db.model.impl.SeliteModelImpl
 * @generated
 */
public interface SeliteModel extends BaseModel<Selite> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a selite model instance should use the {@link Selite} interface instead.
     */

    /**
     * Returns the primary key of this selite.
     *
     * @return the primary key of this selite
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this selite.
     *
     * @param primaryKey the primary key of this selite
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the selite_id of this selite.
     *
     * @return the selite_id of this selite
     */
    public int getSelite_id();

    /**
     * Sets the selite_id of this selite.
     *
     * @param selite_id the selite_id of this selite
     */
    public void setSelite_id(int selite_id);

    /**
     * Returns the nimi of this selite.
     *
     * @return the nimi of this selite
     */
    @AutoEscape
    public String getNimi();

    /**
     * Sets the nimi of this selite.
     *
     * @param nimi the nimi of this selite
     */
    public void setNimi(String nimi);

    /**
     * Returns the name of this selite.
     *
     * @return the name of this selite
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this selite.
     *
     * @param name the name of this selite
     */
    public void setName(String name);

    /**
     * Returns the kuvaus of this selite.
     *
     * @return the kuvaus of this selite
     */
    @AutoEscape
    public String getKuvaus();

    /**
     * Sets the kuvaus of this selite.
     *
     * @param kuvaus the kuvaus of this selite
     */
    public void setKuvaus(String kuvaus);

    /**
     * Returns the description of this selite.
     *
     * @return the description of this selite
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this selite.
     *
     * @param description the description of this selite
     */
    public void setDescription(String description);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Selite selite);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Selite> toCacheModel();

    @Override
    public Selite toEscapedModel();

    @Override
    public Selite toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
