package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Yhteystieto service. Represents a row in the &quot;yhteystieto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.YhteystietoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.YhteystietoImpl}.
 * </p>
 *
 * @author pj,jmlehtin
 * @see Yhteystieto
 * @see fi.csc.avaa.tupa.db.model.impl.YhteystietoImpl
 * @see fi.csc.avaa.tupa.db.model.impl.YhteystietoModelImpl
 * @generated
 */
public interface YhteystietoModel extends BaseModel<Yhteystieto> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a yhteystieto model instance should use the {@link Yhteystieto} interface instead.
     */

    /**
     * Returns the primary key of this yhteystieto.
     *
     * @return the primary key of this yhteystieto
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this yhteystieto.
     *
     * @param primaryKey the primary key of this yhteystieto
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the yhteystieto_id of this yhteystieto.
     *
     * @return the yhteystieto_id of this yhteystieto
     */
    public int getYhteystieto_id();

    /**
     * Sets the yhteystieto_id of this yhteystieto.
     *
     * @param yhteystieto_id the yhteystieto_id of this yhteystieto
     */
    public void setYhteystieto_id(int yhteystieto_id);

    /**
     * Returns the sahkoposti of this yhteystieto.
     *
     * @return the sahkoposti of this yhteystieto
     */
    @AutoEscape
    public String getSahkoposti();

    /**
     * Sets the sahkoposti of this yhteystieto.
     *
     * @param sahkoposti the sahkoposti of this yhteystieto
     */
    public void setSahkoposti(String sahkoposti);

    /**
     * Returns the affiliaatio of this yhteystieto.
     *
     * @return the affiliaatio of this yhteystieto
     */
    public int getAffiliaatio();

    /**
     * Sets the affiliaatio of this yhteystieto.
     *
     * @param affiliaatio the affiliaatio of this yhteystieto
     */
    public void setAffiliaatio(int affiliaatio);

    /**
     * Returns the puhelin of this yhteystieto.
     *
     * @return the puhelin of this yhteystieto
     */
    @AutoEscape
    public String getPuhelin();

    /**
     * Sets the puhelin of this yhteystieto.
     *
     * @param puhelin the puhelin of this yhteystieto
     */
    public void setPuhelin(String puhelin);

    /**
     * Returns the titteli of this yhteystieto.
     *
     * @return the titteli of this yhteystieto
     */
    @AutoEscape
    public String getTitteli();

    /**
     * Sets the titteli of this yhteystieto.
     *
     * @param titteli the titteli of this yhteystieto
     */
    public void setTitteli(String titteli);

    /**
     * Returns the etunimi of this yhteystieto.
     *
     * @return the etunimi of this yhteystieto
     */
    @AutoEscape
    public String getEtunimi();

    /**
     * Sets the etunimi of this yhteystieto.
     *
     * @param etunimi the etunimi of this yhteystieto
     */
    public void setEtunimi(String etunimi);

    /**
     * Returns the sukunimi of this yhteystieto.
     *
     * @return the sukunimi of this yhteystieto
     */
    @AutoEscape
    public String getSukunimi();

    /**
     * Sets the sukunimi of this yhteystieto.
     *
     * @param sukunimi the sukunimi of this yhteystieto
     */
    public void setSukunimi(String sukunimi);

    /**
     * Returns the u r l of this yhteystieto.
     *
     * @return the u r l of this yhteystieto
     */
    @AutoEscape
    public String getURL();

    /**
     * Sets the u r l of this yhteystieto.
     *
     * @param URL the u r l of this yhteystieto
     */
    public void setURL(String URL);

    /**
     * Returns the kuvaus of this yhteystieto.
     *
     * @return the kuvaus of this yhteystieto
     */
    @AutoEscape
    public String getKuvaus();

    /**
     * Sets the kuvaus of this yhteystieto.
     *
     * @param kuvaus the kuvaus of this yhteystieto
     */
    public void setKuvaus(String kuvaus);

    /**
     * Returns the description of this yhteystieto.
     *
     * @return the description of this yhteystieto
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this yhteystieto.
     *
     * @param description the description of this yhteystieto
     */
    public void setDescription(String description);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Yhteystieto yhteystieto);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Yhteystieto> toCacheModel();

    @Override
    public Yhteystieto toEscapedModel();

    @Override
    public Yhteystieto toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
