package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Identifier service. Represents a row in the &quot;identifier&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.IdentifierModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.IdentifierImpl}.
 * </p>
 *
 * @author CSC
 * @see Identifier
 * @see fi.csc.avaa.tupa.db.model.impl.IdentifierImpl
 * @see fi.csc.avaa.tupa.db.model.impl.IdentifierModelImpl
 * @generated
 */
public interface IdentifierModel extends BaseModel<Identifier> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a identifier model instance should use the {@link Identifier} interface instead.
     */

    /**
     * Returns the primary key of this identifier.
     *
     * @return the primary key of this identifier
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this identifier.
     *
     * @param primaryKey the primary key of this identifier
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the identifier_type of this identifier.
     *
     * @return the identifier_type of this identifier
     */
    public int getIdentifier_type();

    /**
     * Sets the identifier_type of this identifier.
     *
     * @param identifier_type the identifier_type of this identifier
     */
    public void setIdentifier_type(int identifier_type);

    /**
     * Returns the identifier_name of this identifier.
     *
     * @return the identifier_name of this identifier
     */
    @AutoEscape
    public String getIdentifier_name();

    /**
     * Sets the identifier_name of this identifier.
     *
     * @param identifier_name the identifier_name of this identifier
     */
    public void setIdentifier_name(String identifier_name);

    /**
     * Returns the identifier_description_translation_key of this identifier.
     *
     * @return the identifier_description_translation_key of this identifier
     */
    @AutoEscape
    public String getIdentifier_description_translation_key();

    /**
     * Sets the identifier_description_translation_key of this identifier.
     *
     * @param identifier_description_translation_key the identifier_description_translation_key of this identifier
     */
    public void setIdentifier_description_translation_key(
        String identifier_description_translation_key);

    /**
     * Returns the resolution_url of this identifier.
     *
     * @return the resolution_url of this identifier
     */
    @AutoEscape
    public String getResolution_url();

    /**
     * Sets the resolution_url of this identifier.
     *
     * @param resolution_url the resolution_url of this identifier
     */
    public void setResolution_url(String resolution_url);

    /**
     * Returns the definition_url of this identifier.
     *
     * @return the definition_url of this identifier
     */
    @AutoEscape
    public String getDefinition_url();

    /**
     * Sets the definition_url of this identifier.
     *
     * @param definition_url the definition_url of this identifier
     */
    public void setDefinition_url(String definition_url);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(fi.csc.avaa.tupa.db.model.Identifier identifier);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.tupa.db.model.Identifier> toCacheModel();

    @Override
    public fi.csc.avaa.tupa.db.model.Identifier toEscapedModel();

    @Override
    public fi.csc.avaa.tupa.db.model.Identifier toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
