package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import fi.csc.avaa.tupa.db.service.persistence.Infra_YhteystiedotPK;

import java.io.Serializable;

/**
 * The base model interface for the Infra_Yhteystiedot service. Represents a row in the &quot;infra_yhteystiedot&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.Infra_YhteystiedotModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.Infra_YhteystiedotImpl}.
 * </p>
 *
 * @author CSC
 * @see Infra_Yhteystiedot
 * @see fi.csc.avaa.tupa.db.model.impl.Infra_YhteystiedotImpl
 * @see fi.csc.avaa.tupa.db.model.impl.Infra_YhteystiedotModelImpl
 * @generated
 */
public interface Infra_YhteystiedotModel extends BaseModel<Infra_Yhteystiedot> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a infra_ yhteystiedot model instance should use the {@link Infra_Yhteystiedot} interface instead.
     */

    /**
     * Returns the primary key of this infra_ yhteystiedot.
     *
     * @return the primary key of this infra_ yhteystiedot
     */
    public Infra_YhteystiedotPK getPrimaryKey();

    /**
     * Sets the primary key of this infra_ yhteystiedot.
     *
     * @param primaryKey the primary key of this infra_ yhteystiedot
     */
    public void setPrimaryKey(Infra_YhteystiedotPK primaryKey);

    /**
     * Returns the infra_id of this infra_ yhteystiedot.
     *
     * @return the infra_id of this infra_ yhteystiedot
     */
    public int getInfra_id();

    /**
     * Sets the infra_id of this infra_ yhteystiedot.
     *
     * @param infra_id the infra_id of this infra_ yhteystiedot
     */
    public void setInfra_id(int infra_id);

    /**
     * Returns the yhteystieto_id of this infra_ yhteystiedot.
     *
     * @return the yhteystieto_id of this infra_ yhteystiedot
     */
    public int getYhteystieto_id();

    /**
     * Sets the yhteystieto_id of this infra_ yhteystiedot.
     *
     * @param yhteystieto_id the yhteystieto_id of this infra_ yhteystiedot
     */
    public void setYhteystieto_id(int yhteystieto_id);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot infra_Yhteystiedot);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot> toCacheModel();

    @Override
    public fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot toEscapedModel();

    @Override
    public fi.csc.avaa.tupa.db.model.Infra_Yhteystiedot toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
