package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Kayttoehto service. Represents a row in the &quot;kayttoehto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.KayttoehtoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.KayttoehtoImpl}.
 * </p>
 *
 * @author CSC
 * @see Kayttoehto
 * @see fi.csc.avaa.tupa.db.model.impl.KayttoehtoImpl
 * @see fi.csc.avaa.tupa.db.model.impl.KayttoehtoModelImpl
 * @generated
 */
public interface KayttoehtoModel extends BaseModel<Kayttoehto> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a kayttoehto model instance should use the {@link Kayttoehto} interface instead.
     */

    /**
     * Returns the primary key of this kayttoehto.
     *
     * @return the primary key of this kayttoehto
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this kayttoehto.
     *
     * @param primaryKey the primary key of this kayttoehto
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the infra_id of this kayttoehto.
     *
     * @return the infra_id of this kayttoehto
     */
    public int getInfra_id();

    /**
     * Sets the infra_id of this kayttoehto.
     *
     * @param infra_id the infra_id of this kayttoehto
     */
    public void setInfra_id(int infra_id);

    /**
     * Returns the saavutettavuus of this kayttoehto.
     *
     * @return the saavutettavuus of this kayttoehto
     */
    public int getSaavutettavuus();

    /**
     * Sets the saavutettavuus of this kayttoehto.
     *
     * @param saavutettavuus the saavutettavuus of this kayttoehto
     */
    public void setSaavutettavuus(int saavutettavuus);

    /**
     * Returns the anonymiteetti of this kayttoehto.
     *
     * @return the anonymiteetti of this kayttoehto
     */
    public int getAnonymiteetti();

    /**
     * Sets the anonymiteetti of this kayttoehto.
     *
     * @param anonymiteetti the anonymiteetti of this kayttoehto
     */
    public void setAnonymiteetti(int anonymiteetti);

    /**
     * Returns the maksullisuus of this kayttoehto.
     *
     * @return the maksullisuus of this kayttoehto
     */
    public int getMaksullisuus();

    /**
     * Sets the maksullisuus of this kayttoehto.
     *
     * @param maksullisuus the maksullisuus of this kayttoehto
     */
    public void setMaksullisuus(int maksullisuus);

    /**
     * Returns the tulosten_julkaisuvelvoite of this kayttoehto.
     *
     * @return the tulosten_julkaisuvelvoite of this kayttoehto
     */
    public int getTulosten_julkaisuvelvoite();

    /**
     * Sets the tulosten_julkaisuvelvoite of this kayttoehto.
     *
     * @param tulosten_julkaisuvelvoite the tulosten_julkaisuvelvoite of this kayttoehto
     */
    public void setTulosten_julkaisuvelvoite(int tulosten_julkaisuvelvoite);

    /**
     * Returns the tuotoksien_julkaisuvelvoite of this kayttoehto.
     *
     * @return the tuotoksien_julkaisuvelvoite of this kayttoehto
     */
    public int getTuotoksien_julkaisuvelvoite();

    /**
     * Sets the tuotoksien_julkaisuvelvoite of this kayttoehto.
     *
     * @param tuotoksien_julkaisuvelvoite the tuotoksien_julkaisuvelvoite of this kayttoehto
     */
    public void setTuotoksien_julkaisuvelvoite(int tuotoksien_julkaisuvelvoite);

    /**
     * Returns the osaamisen_avoimuus of this kayttoehto.
     *
     * @return the osaamisen_avoimuus of this kayttoehto
     */
    public int getOsaamisen_avoimuus();

    /**
     * Sets the osaamisen_avoimuus of this kayttoehto.
     *
     * @param osaamisen_avoimuus the osaamisen_avoimuus of this kayttoehto
     */
    public void setOsaamisen_avoimuus(int osaamisen_avoimuus);

    /**
     * Returns the seurantatyokalut of this kayttoehto.
     *
     * @return the seurantatyokalut of this kayttoehto
     */
    public int getSeurantatyokalut();

    /**
     * Sets the seurantatyokalut of this kayttoehto.
     *
     * @param seurantatyokalut the seurantatyokalut of this kayttoehto
     */
    public void setSeurantatyokalut(int seurantatyokalut);

    /**
     * Returns the tulosten_lisensointi of this kayttoehto.
     *
     * @return the tulosten_lisensointi of this kayttoehto
     */
    public int getTulosten_lisensointi();

    /**
     * Sets the tulosten_lisensointi of this kayttoehto.
     *
     * @param tulosten_lisensointi the tulosten_lisensointi of this kayttoehto
     */
    public void setTulosten_lisensointi(int tulosten_lisensointi);

    /**
     * Returns the u r lfi of this kayttoehto.
     *
     * @return the u r lfi of this kayttoehto
     */
    @AutoEscape
    public String getURLfi();

    /**
     * Sets the u r lfi of this kayttoehto.
     *
     * @param URLfi the u r lfi of this kayttoehto
     */
    public void setURLfi(String URLfi);

    /**
     * Returns the u r len of this kayttoehto.
     *
     * @return the u r len of this kayttoehto
     */
    @AutoEscape
    public String getURLen();

    /**
     * Sets the u r len of this kayttoehto.
     *
     * @param URLen the u r len of this kayttoehto
     */
    public void setURLen(String URLen);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(fi.csc.avaa.tupa.db.model.Kayttoehto kayttoehto);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.tupa.db.model.Kayttoehto> toCacheModel();

    @Override
    public fi.csc.avaa.tupa.db.model.Kayttoehto toEscapedModel();

    @Override
    public fi.csc.avaa.tupa.db.model.Kayttoehto toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
