package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TpAPI service. Represents a row in the &quot;tupa_TpAPI&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.TpAPIModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.TpAPIImpl}.
 * </p>
 *
 * @author CSC
 * @see TpAPI
 * @see fi.csc.avaa.tupa.db.model.impl.TpAPIImpl
 * @see fi.csc.avaa.tupa.db.model.impl.TpAPIModelImpl
 * @generated
 */
public interface TpAPIModel extends BaseModel<TpAPI> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a tp a p i model instance should use the {@link TpAPI} interface instead.
     */

    /**
     * Returns the primary key of this tp a p i.
     *
     * @return the primary key of this tp a p i
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this tp a p i.
     *
     * @param primaryKey the primary key of this tp a p i
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the methods description of this tp a p i.
     *
     * @return the methods description of this tp a p i
     */
    @AutoEscape
    public String getMethodsDescription();

    /**
     * Sets the methods description of this tp a p i.
     *
     * @param methodsDescription the methods description of this tp a p i
     */
    public void setMethodsDescription(String methodsDescription);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(fi.csc.avaa.tupa.db.model.TpAPI tpAPI);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.tupa.db.model.TpAPI> toCacheModel();

    @Override
    public fi.csc.avaa.tupa.db.model.TpAPI toEscapedModel();

    @Override
    public fi.csc.avaa.tupa.db.model.TpAPI toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
