package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TpContact service. Represents a row in the &quot;tupa_TpContact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.TpContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.TpContactImpl}.
 * </p>
 *
 * @author CSC
 * @see TpContact
 * @see fi.csc.avaa.tupa.db.model.impl.TpContactImpl
 * @see fi.csc.avaa.tupa.db.model.impl.TpContactModelImpl
 * @generated
 */
public interface TpContactModel extends BaseModel<TpContact> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a tp contact model instance should use the {@link TpContact} interface instead.
     */

    /**
     * Returns the primary key of this tp contact.
     *
     * @return the primary key of this tp contact
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this tp contact.
     *
     * @param primaryKey the primary key of this tp contact
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the ID of this tp contact.
     *
     * @return the ID of this tp contact
     */
    public int getId();

    /**
     * Sets the ID of this tp contact.
     *
     * @param id the ID of this tp contact
     */
    public void setId(int id);

    /**
     * Returns the email of this tp contact.
     *
     * @return the email of this tp contact
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this tp contact.
     *
     * @param email the email of this tp contact
     */
    public void setEmail(String email);

    /**
     * Returns the phone of this tp contact.
     *
     * @return the phone of this tp contact
     */
    @AutoEscape
    public String getPhone();

    /**
     * Sets the phone of this tp contact.
     *
     * @param phone the phone of this tp contact
     */
    public void setPhone(String phone);

    /**
     * Returns the title of this tp contact.
     *
     * @return the title of this tp contact
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this tp contact.
     *
     * @param title the title of this tp contact
     */
    public void setTitle(String title);

    /**
     * Returns the first name of this tp contact.
     *
     * @return the first name of this tp contact
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this tp contact.
     *
     * @param firstName the first name of this tp contact
     */
    public void setFirstName(String firstName);

    /**
     * Returns the last name of this tp contact.
     *
     * @return the last name of this tp contact
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this tp contact.
     *
     * @param lastName the last name of this tp contact
     */
    public void setLastName(String lastName);

    /**
     * Returns the url of this tp contact.
     *
     * @return the url of this tp contact
     */
    @AutoEscape
    public String getUrl();

    /**
     * Sets the url of this tp contact.
     *
     * @param url the url of this tp contact
     */
    public void setUrl(String url);

    /**
     * Returns the description_ e n of this tp contact.
     *
     * @return the description_ e n of this tp contact
     */
    @AutoEscape
    public String getDescription_EN();

    /**
     * Sets the description_ e n of this tp contact.
     *
     * @param description_EN the description_ e n of this tp contact
     */
    public void setDescription_EN(String description_EN);

    /**
     * Returns the description_ f i of this tp contact.
     *
     * @return the description_ f i of this tp contact
     */
    @AutoEscape
    public String getDescription_FI();

    /**
     * Sets the description_ f i of this tp contact.
     *
     * @param description_FI the description_ f i of this tp contact
     */
    public void setDescription_FI(String description_FI);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(fi.csc.avaa.tupa.db.model.TpContact tpContact);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.tupa.db.model.TpContact> toCacheModel();

    @Override
    public fi.csc.avaa.tupa.db.model.TpContact toEscapedModel();

    @Override
    public fi.csc.avaa.tupa.db.model.TpContact toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
