package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TpInfrastructure service. Represents a row in the &quot;tupa_TpInfrastructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.TpInfrastructureModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.TpInfrastructureImpl}.
 * </p>
 *
 * @author CSC
 * @see TpInfrastructure
 * @see fi.csc.avaa.tupa.db.model.impl.TpInfrastructureImpl
 * @see fi.csc.avaa.tupa.db.model.impl.TpInfrastructureModelImpl
 * @generated
 */
public interface TpInfrastructureModel extends BaseModel<TpInfrastructure> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a tp infrastructure model instance should use the {@link TpInfrastructure} interface instead.
     */

    /**
     * Returns the primary key of this tp infrastructure.
     *
     * @return the primary key of this tp infrastructure
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this tp infrastructure.
     *
     * @param primaryKey the primary key of this tp infrastructure
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the ID of this tp infrastructure.
     *
     * @return the ID of this tp infrastructure
     */
    public int getId();

    /**
     * Sets the ID of this tp infrastructure.
     *
     * @param id the ID of this tp infrastructure
     */
    public void setId(int id);

    /**
     * Returns the urn of this tp infrastructure.
     *
     * @return the urn of this tp infrastructure
     */
    @AutoEscape
    public String getUrn();

    /**
     * Sets the urn of this tp infrastructure.
     *
     * @param urn the urn of this tp infrastructure
     */
    public void setUrn(String urn);

    /**
     * Returns the name_ e n of this tp infrastructure.
     *
     * @return the name_ e n of this tp infrastructure
     */
    @AutoEscape
    public String getName_EN();

    /**
     * Sets the name_ e n of this tp infrastructure.
     *
     * @param name_EN the name_ e n of this tp infrastructure
     */
    public void setName_EN(String name_EN);

    /**
     * Returns the name_ f i of this tp infrastructure.
     *
     * @return the name_ f i of this tp infrastructure
     */
    @AutoEscape
    public String getName_FI();

    /**
     * Sets the name_ f i of this tp infrastructure.
     *
     * @param name_FI the name_ f i of this tp infrastructure
     */
    public void setName_FI(String name_FI);

    /**
     * Returns the acronym_ e n of this tp infrastructure.
     *
     * @return the acronym_ e n of this tp infrastructure
     */
    @AutoEscape
    public String getAcronym_EN();

    /**
     * Sets the acronym_ e n of this tp infrastructure.
     *
     * @param acronym_EN the acronym_ e n of this tp infrastructure
     */
    public void setAcronym_EN(String acronym_EN);

    /**
     * Returns the acronym_ f i of this tp infrastructure.
     *
     * @return the acronym_ f i of this tp infrastructure
     */
    @AutoEscape
    public String getAcronym_FI();

    /**
     * Sets the acronym_ f i of this tp infrastructure.
     *
     * @param acronym_FI the acronym_ f i of this tp infrastructure
     */
    public void setAcronym_FI(String acronym_FI);

    /**
     * Returns the description_ e n of this tp infrastructure.
     *
     * @return the description_ e n of this tp infrastructure
     */
    @AutoEscape
    public String getDescription_EN();

    /**
     * Sets the description_ e n of this tp infrastructure.
     *
     * @param description_EN the description_ e n of this tp infrastructure
     */
    public void setDescription_EN(String description_EN);

    /**
     * Returns the description_ f i of this tp infrastructure.
     *
     * @return the description_ f i of this tp infrastructure
     */
    @AutoEscape
    public String getDescription_FI();

    /**
     * Sets the description_ f i of this tp infrastructure.
     *
     * @param description_FI the description_ f i of this tp infrastructure
     */
    public void setDescription_FI(String description_FI);

    /**
     * Returns the active of this tp infrastructure.
     *
     * @return the active of this tp infrastructure
     */
    public boolean getActive();

    /**
     * Returns <code>true</code> if this tp infrastructure is active.
     *
     * @return <code>true</code> if this tp infrastructure is active; <code>false</code> otherwise
     */
    public boolean isActive();

    /**
     * Sets whether this tp infrastructure is active.
     *
     * @param active the active of this tp infrastructure
     */
    public void setActive(boolean active);

    /**
     * Returns the preparations started of this tp infrastructure.
     *
     * @return the preparations started of this tp infrastructure
     */
    public int getPreparationsStarted();

    /**
     * Sets the preparations started of this tp infrastructure.
     *
     * @param preparationsStarted the preparations started of this tp infrastructure
     */
    public void setPreparationsStarted(int preparationsStarted);

    /**
     * Returns the building started of this tp infrastructure.
     *
     * @return the building started of this tp infrastructure
     */
    public int getBuildingStarted();

    /**
     * Sets the building started of this tp infrastructure.
     *
     * @param buildingStarted the building started of this tp infrastructure
     */
    public void setBuildingStarted(int buildingStarted);

    /**
     * Returns the operations started of this tp infrastructure.
     *
     * @return the operations started of this tp infrastructure
     */
    public int getOperationsStarted();

    /**
     * Sets the operations started of this tp infrastructure.
     *
     * @param operationsStarted the operations started of this tp infrastructure
     */
    public void setOperationsStarted(int operationsStarted);

    /**
     * Returns the operations finished of this tp infrastructure.
     *
     * @return the operations finished of this tp infrastructure
     */
    public int getOperationsFinished();

    /**
     * Sets the operations finished of this tp infrastructure.
     *
     * @param operationsFinished the operations finished of this tp infrastructure
     */
    public void setOperationsFinished(int operationsFinished);

    /**
     * Returns the former IDs of this tp infrastructure.
     *
     * @return the former IDs of this tp infrastructure
     */
    @AutoEscape
    public String getFormerIds();

    /**
     * Sets the former IDs of this tp infrastructure.
     *
     * @param formerIds the former IDs of this tp infrastructure
     */
    public void setFormerIds(String formerIds);

    /**
     * Returns the former urns of this tp infrastructure.
     *
     * @return the former urns of this tp infrastructure
     */
    @AutoEscape
    public String getFormerUrns();

    /**
     * Sets the former urns of this tp infrastructure.
     *
     * @param formerUrns the former urns of this tp infrastructure
     */
    public void setFormerUrns(String formerUrns);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        fi.csc.avaa.tupa.db.model.TpInfrastructure tpInfrastructure);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.tupa.db.model.TpInfrastructure> toCacheModel();

    @Override
    public fi.csc.avaa.tupa.db.model.TpInfrastructure toEscapedModel();

    @Override
    public fi.csc.avaa.tupa.db.model.TpInfrastructure toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
