package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TpOrganisation service. Represents a row in the &quot;tupa_TpOrganisation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.TpOrganisationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.TpOrganisationImpl}.
 * </p>
 *
 * @author CSC
 * @see TpOrganisation
 * @see fi.csc.avaa.tupa.db.model.impl.TpOrganisationImpl
 * @see fi.csc.avaa.tupa.db.model.impl.TpOrganisationModelImpl
 * @generated
 */
public interface TpOrganisationModel extends BaseModel<TpOrganisation> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a tp organisation model instance should use the {@link TpOrganisation} interface instead.
     */

    /**
     * Returns the primary key of this tp organisation.
     *
     * @return the primary key of this tp organisation
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this tp organisation.
     *
     * @param primaryKey the primary key of this tp organisation
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the ID of this tp organisation.
     *
     * @return the ID of this tp organisation
     */
    public int getId();

    /**
     * Sets the ID of this tp organisation.
     *
     * @param id the ID of this tp organisation
     */
    public void setId(int id);

    /**
     * Returns the name_ e n of this tp organisation.
     *
     * @return the name_ e n of this tp organisation
     */
    @AutoEscape
    public String getName_EN();

    /**
     * Sets the name_ e n of this tp organisation.
     *
     * @param name_EN the name_ e n of this tp organisation
     */
    public void setName_EN(String name_EN);

    /**
     * Returns the name_ f i of this tp organisation.
     *
     * @return the name_ f i of this tp organisation
     */
    @AutoEscape
    public String getName_FI();

    /**
     * Sets the name_ f i of this tp organisation.
     *
     * @param name_FI the name_ f i of this tp organisation
     */
    public void setName_FI(String name_FI);

    /**
     * Returns the isni of this tp organisation.
     *
     * @return the isni of this tp organisation
     */
    @AutoEscape
    public String getIsni();

    /**
     * Sets the isni of this tp organisation.
     *
     * @param isni the isni of this tp organisation
     */
    public void setIsni(String isni);

    /**
     * Returns the mother organisations IDs of this tp organisation.
     *
     * @return the mother organisations IDs of this tp organisation
     */
    public int getMotherOrganisationsIds();

    /**
     * Sets the mother organisations IDs of this tp organisation.
     *
     * @param motherOrganisationsIds the mother organisations IDs of this tp organisation
     */
    public void setMotherOrganisationsIds(int motherOrganisationsIds);

    /**
     * Returns the country of this tp organisation.
     *
     * @return the country of this tp organisation
     */
    @AutoEscape
    public String getCountry();

    /**
     * Sets the country of this tp organisation.
     *
     * @param country the country of this tp organisation
     */
    public void setCountry(String country);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        fi.csc.avaa.tupa.db.model.TpOrganisation tpOrganisation);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.tupa.db.model.TpOrganisation> toCacheModel();

    @Override
    public fi.csc.avaa.tupa.db.model.TpOrganisation toEscapedModel();

    @Override
    public fi.csc.avaa.tupa.db.model.TpOrganisation toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
