package fi.csc.avaa.tupa.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TpServize service. Represents a row in the &quot;tupa_TpServize&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.tupa.db.model.impl.TpServizeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.tupa.db.model.impl.TpServizeImpl}.
 * </p>
 *
 * @author CSC
 * @see TpServize
 * @see fi.csc.avaa.tupa.db.model.impl.TpServizeImpl
 * @see fi.csc.avaa.tupa.db.model.impl.TpServizeModelImpl
 * @generated
 */
public interface TpServizeModel extends BaseModel<TpServize> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a tp servize model instance should use the {@link TpServize} interface instead.
     */

    /**
     * Returns the primary key of this tp servize.
     *
     * @return the primary key of this tp servize
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this tp servize.
     *
     * @param primaryKey the primary key of this tp servize
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the ID of this tp servize.
     *
     * @return the ID of this tp servize
     */
    public int getId();

    /**
     * Sets the ID of this tp servize.
     *
     * @param id the ID of this tp servize
     */
    public void setId(int id);

    /**
     * Returns the name_ e n of this tp servize.
     *
     * @return the name_ e n of this tp servize
     */
    @AutoEscape
    public String getName_EN();

    /**
     * Sets the name_ e n of this tp servize.
     *
     * @param name_EN the name_ e n of this tp servize
     */
    public void setName_EN(String name_EN);

    /**
     * Returns the name_ f i of this tp servize.
     *
     * @return the name_ f i of this tp servize
     */
    @AutoEscape
    public String getName_FI();

    /**
     * Sets the name_ f i of this tp servize.
     *
     * @param name_FI the name_ f i of this tp servize
     */
    public void setName_FI(String name_FI);

    /**
     * Returns the description_ e n of this tp servize.
     *
     * @return the description_ e n of this tp servize
     */
    @AutoEscape
    public String getDescription_EN();

    /**
     * Sets the description_ e n of this tp servize.
     *
     * @param description_EN the description_ e n of this tp servize
     */
    public void setDescription_EN(String description_EN);

    /**
     * Returns the description_ f i of this tp servize.
     *
     * @return the description_ f i of this tp servize
     */
    @AutoEscape
    public String getDescription_FI();

    /**
     * Sets the description_ f i of this tp servize.
     *
     * @param description_FI the description_ f i of this tp servize
     */
    public void setDescription_FI(String description_FI);

    /**
     * Returns the url of this tp servize.
     *
     * @return the url of this tp servize
     */
    @AutoEscape
    public String getUrl();

    /**
     * Sets the url of this tp servize.
     *
     * @param url the url of this tp servize
     */
    public void setUrl(String url);

    /**
     * Returns the address of this tp servize.
     *
     * @return the address of this tp servize
     */
    @AutoEscape
    public String getAddress();

    /**
     * Sets the address of this tp servize.
     *
     * @param address the address of this tp servize
     */
    public void setAddress(String address);

    /**
     * Returns the city of this tp servize.
     *
     * @return the city of this tp servize
     */
    @AutoEscape
    public String getCity();

    /**
     * Sets the city of this tp servize.
     *
     * @param city the city of this tp servize
     */
    public void setCity(String city);

    /**
     * Returns the lat of this tp servize.
     *
     * @return the lat of this tp servize
     */
    public double getLat();

    /**
     * Sets the lat of this tp servize.
     *
     * @param lat the lat of this tp servize
     */
    public void setLat(double lat);

    /**
     * Returns the lon of this tp servize.
     *
     * @return the lon of this tp servize
     */
    public double getLon();

    /**
     * Sets the lon of this tp servize.
     *
     * @param lon the lon of this tp servize
     */
    public void setLon(double lon);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(fi.csc.avaa.tupa.db.model.TpServize tpServize);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.tupa.db.model.TpServize> toCacheModel();

    @Override
    public fi.csc.avaa.tupa.db.model.TpServize toEscapedModel();

    @Override
    public fi.csc.avaa.tupa.db.model.TpServize toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
